a: a.cpp
	g++ a.cpp -std=c++17 -I .
	./a.out
	python3 exp.py a.cpp
	clang-format combined.cpp | clip.exe

b: b.cpp
	g++ b.cpp -std=c++17 -I .
	./a.out
	python3 exp.py b.cpp
	clang-format combined.cpp | clip.exe

c: c.cpp
	g++ c.cpp -std=c++17 -I .
	./a.out
	python3 exp.py c.cpp
	clang-format combined.cpp | clip.exe

d: d.cpp
	g++ d.cpp -std=c++17 -I .
	./a.out
	python3 exp.py d.cpp
	clang-format combined.cpp | clip.exe

e: e.cpp
	g++ e.cpp -std=c++17 -I .
	./a.out
	python3 exp.py e.cpp
	clang-format combined.cpp | clip.exe

f: f.cpp
	g++ f.cpp -std=c++17 -I .
	./a.out
	python3 exp.py f.cpp
	clang-format combined.cpp | clip.exe

g: g.cpp
	g++ g.cpp -std=c++17 -I .
	./a.out
	python3 exp.py g.cpp
	clang-format combined.cpp | clip.exe

h: h.cpp
	g++ h.cpp -std=c++17 -I .
	./a.out
	python3 exp.py h.cpp
	clang-format combined.cpp | clip.exe

t: a.cpp
	g++ a.cpp -std=c++17 -D=LOCAL -I .
	./a.out

ta: a.cpp
	g++ a.cpp -std=c++17 -D=LOCAL -I .
	./a.out

tb: b.cpp
	g++ b.cpp -std=c++17 -D=LOCAL -I .
	./a.out

tc: c.cpp
	g++ c.cpp -std=c++17 -D=LOCAL -I .
	./a.out

td: d.cpp
	g++ d.cpp -std=c++17 -D=LOCAL -I .
	./a.out

te: e.cpp
	g++ e.cpp -std=c++17 -D=LOCAL -I .
	./a.out

tf: f.cpp
	g++ f.cpp -std=c++17 -D=LOCAL -I .
	./a.out

tg: g.cpp
	g++ g.cpp -std=c++17 -D=LOCAL -I .
	./a.out

th: h.cpp
	g++ h.cpp -std=c++17 -D=LOCAL -I .
	./a.out


p: a.py
	cp a.py combined.py 
	black combined.py
	python3 a.py
	cat combined.py | clip.exe

pa: a.py
	cp a.py combined.py 
	black combined.py
	python3 a.py
	cat combined.py | clip.exe


pb: b.py
	cp b.py combined.py 
	black combined.py
	python3 b.py
	cat combined.py | clip.exe

pc: c.py
	cp c.py combined.py 
	black combined.py
	python3 c.py
	cat combined.py | clip.exe

pd: d.py
	cp d.py combined.py 
	black combined.py
	python3 d.py
	cat combined.py | clip.exe

pe: e.py
	cp e.py combined.py 
	black combined.py
	python3 e.py
	cat combined.py | clip.exe

pf: f.py
	cp f.py combined.py 
	black combined.py
	python3 f.py
	cat combined.py | clip.exe

pg: g.py
	cp g.py combined.py 
	black combined.py
	python3 g.py
	cat combined.py | clip.exe



