a: a.cpp
	g++ a.cpp -std=c++20 -I . -O2
	./a.out
	python3 exp.py a.cpp
	clang-format combined.cpp | pbcopy

b: b.cpp
	g++ b.cpp -std=c++20 -I . -O2
	./a.out
	python3 exp.py b.cpp
	clang-format combined.cpp | pbcopy

c: c.cpp
	g++ c.cpp -std=c++20 -I . -O2
	./a.out
	python3 exp.py c.cpp
	clang-format combined.cpp | pbcopy

d: d.cpp
	g++ d.cpp -std=c++20 -I . -O2
	./a.out
	python3 exp.py d.cpp
	clang-format combined.cpp | pbcopy

e: e.cpp
	g++ e.cpp -std=c++20 -I . -O2
	./a.out
	python3 exp.py e.cpp
	clang-format combined.cpp | pbcopy

f: f.cpp
	g++ f.cpp -std=c++20 -I . -O2
	./a.out
	python3 exp.py f.cpp
	clang-format combined.cpp | pbcopy

g: g.cpp
	g++ g.cpp -std=c++20 -I . -O2
	./a.out
	python3 exp.py g.cpp
	clang-format combined.cpp | pbcopy

h: h.cpp
	g++ h.cpp -std=c++20 -I . -O2
	./a.out
	python3 exp.py h.cpp
	clang-format combined.cpp | pbcopy

t: a.cpp
	g++ a.cpp -std=c++20 -D=LOCAL -I . -O2
	./a.out

ta: a.cpp
	g++ a.cpp -std=c++20 -D=LOCAL -I . -O2
	./a.out

tb: b.cpp
	g++ b.cpp -std=c++20 -D=LOCAL -I . -O2
	./a.out

tc: c.cpp
	g++ c.cpp -std=c++20 -D=LOCAL -I . -O2
	./a.out

td: d.cpp
	g++ d.cpp -std=c++20 -D=LOCAL -I . -O2
	./a.out

te: e.cpp
	g++ e.cpp -std=c++20 -D=LOCAL -I . -O2
	./a.out

tf: f.cpp
	g++ f.cpp -std=c++20 -D=LOCAL -I . -O2
	./a.out

tg: g.cpp
	g++ g.cpp -std=c++20 -D=LOCAL -I . -O2
	./a.out

th: h.cpp
	g++ h.cpp -std=c++20 -D=LOCAL -I . -O2
	./a.out


p: a.py
	python3 a.py
	cat a.py | pbcopy

pa: a.py
	python3 a.py
	cat a.py | pbcopy

pb: b.py
	python3 b.py
	cat b.py | pbcopy

pc: c.py
	python3 c.py
	cat c.py | pbcopy

pd: d.py
	python3 d.py
	cat d.py | pbcopy

pe: e.py
	python3 e.py
	cat e.py | pbcopy
