.TH "math ディレクトリリファレンス" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math ディレクトリリファレンス
.SH SYNOPSIS
.br
.PP
.SS "ファイル"

.in +1c
.ti -1c
.RI "ファイル \fBbezout_identity\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBconvolution\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBconvolution_ll\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBextgcd\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBfactors\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBfps\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBfraction\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBlagrange\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBlagrange2\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBlinear_equation\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBlinear_programming_2vars\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBmatrix\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBmodlog\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBmultipoint_evaluate\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBntt\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBntt998\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBprimality_test\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBprime_enumerate\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBprime_factorize\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBprimitive_root\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBtotient\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBtotient_table\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBxor_convolution\&.hpp\fP"
.br
.in -1c
