.TH "data_structure ディレクトリリファレンス" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_structure ディレクトリリファレンス
.SH SYNOPSIS
.br
.PP
.SS "ファイル"

.in +1c
.ti -1c
.RI "ファイル \fBbinary_trie\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBcumulative_sum_2d\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBfenwick_tree\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBinsert_reverse_array\&.hpp\fP"
.br
.RI "挿入・削除・区間反転可能な配列 \fBhttps://nyaannyaan.github.io/library/rbst/lazy-reversible-rbst.hpp.html\fP "
.ti -1c
.RI "ファイル \fBmerge_sort_tree\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBmultiset\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBoffset_vector\&.hpp\fP"
.br
.RI "負の添字を取れる vector "
.ti -1c
.RI "ファイル \fBrange_set\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBsegtree\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBsegtree_2d\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBsegtree_beats\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBsegtree_dual\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBsegtree_dynamic\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBsegtree_lazy\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBset\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBsorted_multitree\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBsorted_tree\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBsparse_table\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBsparse_table_2d\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBsparse_table_disjoint\&.hpp\fP"
.br
.ti -1c
.RI "ファイル \fBwavelet_matrix\&.hpp\fP"
.br
.in -1c
