.TH "Abel::Xor< T >" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Abel::Xor< T > \- XOR  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'abel\&.hpp'\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "using \fBType\fP = T"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBType\fP \fBid\fP ()"
.br
.ti -1c
.RI "static \fBType\fP \fBop\fP (const \fBType\fP &a, const \fBType\fP &b)"
.br
.ti -1c
.RI "static \fBType\fP \fBinv\fP (const \fBType\fP &x)"
.br
.in -1c
.SH "詳解"
.PP 

.SS "template<typename T>
.br
struct Abel::Xor< T >"XOR 
.PP
 \fBabel\&.hpp\fP の \fB17\fP 行目に定義があります。
.SH "型定義メンバ詳解"
.PP 
.SS "template<typename T> using \fBAbel::Xor\fP< T >::Type = T"

.PP
 \fBabel\&.hpp\fP の \fB18\fP 行目に定義があります。
.SH "関数詳解"
.PP 
.SS "template<typename T> static \fBType\fP \fBAbel::Xor\fP< T >::id ()\fR [inline]\fP, \fR [static]\fP"

.PP
 \fBabel\&.hpp\fP の \fB19\fP 行目に定義があります。
.SS "template<typename T> static \fBType\fP \fBAbel::Xor\fP< T >::op (const \fBType\fP & a, const \fBType\fP & b)\fR [inline]\fP, \fR [static]\fP"

.PP
 \fBabel\&.hpp\fP の \fB20\fP 行目に定義があります。
.SS "template<typename T> static \fBType\fP \fBAbel::Xor\fP< T >::inv (const \fBType\fP & x)\fR [inline]\fP, \fR [static]\fP"

.PP
 \fBabel\&.hpp\fP の \fB21\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
