.TH "others/abel.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
others/abel.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBAbel::Sum< T >\fP"
.br
.RI "和 "
.ti -1c
.RI "struct \fBAbel::Xor< T >\fP"
.br
.RI "XOR "
.in -1c
.SS "名前空間"

.in +1c
.ti -1c
.RI "namespace \fBAbel\fP"
.br
.RI "可換群 "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
