.TH "AngelBeats::Node" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AngelBeats::Node
.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'segtree_beats\&.hpp'\fP
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBll\fP \fBsum\fP = 0"
.br
.ti -1c
.RI "\fBll\fP \fBg1\fP = 0"
.br
.ti -1c
.RI "\fBll\fP \fBl1\fP = 0"
.br
.ti -1c
.RI "\fBll\fP \fBg2\fP = \-\fBINFL\fP"
.br
.ti -1c
.RI "\fBll\fP \fBgc\fP = 1"
.br
.ti -1c
.RI "\fBll\fP \fBl2\fP = \fBINFL\fP"
.br
.ti -1c
.RI "\fBll\fP \fBlc\fP = 1"
.br
.ti -1c
.RI "\fBll\fP \fBadd\fP = 0"
.br
.in -1c
.SH "詳解"
.PP 
 \fBsegtree_beats\&.hpp\fP の \fB6\fP 行目に定義があります。
.SH "メンバ詳解"
.PP 
.SS "\fBll\fP AngelBeats::Node::sum = 0"

.PP
 \fBsegtree_beats\&.hpp\fP の \fB7\fP 行目に定義があります。
.SS "\fBll\fP AngelBeats::Node::g1 = 0"

.PP
 \fBsegtree_beats\&.hpp\fP の \fB7\fP 行目に定義があります。
.SS "\fBll\fP AngelBeats::Node::l1 = 0"

.PP
 \fBsegtree_beats\&.hpp\fP の \fB7\fP 行目に定義があります。
.SS "\fBll\fP AngelBeats::Node::g2 = \-\fBINFL\fP"

.PP
 \fBsegtree_beats\&.hpp\fP の \fB8\fP 行目に定義があります。
.SS "\fBll\fP AngelBeats::Node::gc = 1"

.PP
 \fBsegtree_beats\&.hpp\fP の \fB8\fP 行目に定義があります。
.SS "\fBll\fP AngelBeats::Node::l2 = \fBINFL\fP"

.PP
 \fBsegtree_beats\&.hpp\fP の \fB8\fP 行目に定義があります。
.SS "\fBll\fP AngelBeats::Node::lc = 1"

.PP
 \fBsegtree_beats\&.hpp\fP の \fB8\fP 行目に定義があります。
.SS "\fBll\fP AngelBeats::Node::add = 0"

.PP
 \fBsegtree_beats\&.hpp\fP の \fB8\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
