.TH "geometry/argsort.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
geometry/argsort.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "void \fBargsort\fP (vector< pair< \fBll\fP, \fBll\fP > > &xy)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "void argsort (vector< pair< \fBll\fP, \fBll\fP > > & xy)"

.PP
 \fBargsort\&.hpp\fP の \fB3\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
