.TH "ArithmeticProgression" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArithmeticProgression \- 等差数列  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'arithmetic_sum\&.hpp'\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "void \fBnormalize\fP ()"
.br
.RI "初項、公差、末項、項数のうち、足りない情報を計算する "
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBll\fP \fBstart\fP =\fBINFL\fP"
.br
.ti -1c
.RI "\fBll\fP \fBgoal\fP =\fBINFL\fP"
.br
.ti -1c
.RI "\fBll\fP \fBstep\fP =\fBINFL\fP"
.br
.ti -1c
.RI "\fBll\fP \fBlength\fP =\fBINFL\fP"
.br
.in -1c
.SH "詳解"
.PP 
等差数列 
.PP
 \fBarithmetic_sum\&.hpp\fP の \fB4\fP 行目に定義があります。
.SH "関数詳解"
.PP 
.SS "void ArithmeticProgression::normalize ()\fR [inline]\fP"

.PP
初項、公差、末項、項数のうち、足りない情報を計算する 
.PP
 \fBarithmetic_sum\&.hpp\fP の \fB8\fP 行目に定義があります。
.PP
参照先 \fBgoal\fP, \fBINFL\fP, \fBlength\fP, \fBstart\fP, \fBstep\fP\&.
.SH "メンバ詳解"
.PP 
.SS "\fBll\fP ArithmeticProgression::start =\fBINFL\fP"

.PP
 \fBarithmetic_sum\&.hpp\fP の \fB5\fP 行目に定義があります。
.SS "\fBll\fP ArithmeticProgression::goal =\fBINFL\fP"

.PP
 \fBarithmetic_sum\&.hpp\fP の \fB5\fP 行目に定義があります。
.SS "\fBll\fP ArithmeticProgression::step =\fBINFL\fP"

.PP
 \fBarithmetic_sum\&.hpp\fP の \fB5\fP 行目に定義があります。
.SS "\fBll\fP ArithmeticProgression::length =\fBINFL\fP"

.PP
 \fBarithmetic_sum\&.hpp\fP の \fB5\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
