.TH "others/arithmetic_sum.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
others/arithmetic_sum.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBArithmeticProgression\fP"
.br
.RI "等差数列 "
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "\fBll\fP \fBArithmeticSum\fP (\fBArithmeticProgression\fP ap)"
.br
.RI "等差数列の和を返す "
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBll\fP ArithmeticSum (\fBArithmeticProgression\fP ap)"

.PP
等差数列の和を返す 
.PP
 \fBarithmetic_sum\&.hpp\fP の \fB26\fP 行目に定義があります。
.PP
参照先 \fBArithmeticProgression::goal\fP, \fBArithmeticProgression::length\fP, \fBArithmeticProgression::normalize()\fP, \fBArithmeticProgression::start\fP\&.
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
