.TH "graph/shortest_path/bfs.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph/shortest_path/bfs.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "\fBVL\fP \fBBFS\fP (const \fBVVI\fP &g, int start=0)"
.br
.RI "重みなしグラフ g の頂点 start からの最短距離を求める "
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBVL\fP BFS (const \fBVVI\fP & g, int start = \fR0\fP)"

.PP
重みなしグラフ g の頂点 start からの最短距離を求める 
.PP
\fB覚え書き\fP
.RS 4
O(E+V) 
.RE
.PP

.PP
 \fBbfs\&.hpp\fP の \fB5\fP 行目に定義があります。
.PP
参照先 \fBINF\fP\&.
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
