.TH "BiInfo" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BiInfo \- 二部グラフのパラメータ  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'bipartite_matching\&.hpp'\fP
.SS "公開変数類"

.in +1c
.ti -1c
.RI "int \fBmax_matching\fP"
.br
.RI "最大マッチング "
.ti -1c
.RI "int \fBmin_edge_cover\fP"
.br
.RI "最小辺被覆 "
.ti -1c
.RI "int \fBmax_independent_set\fP"
.br
.RI "最大独立集合 "
.ti -1c
.RI "int \fBmin_vertex_cover\fP"
.br
.in -1c
.SH "詳解"
.PP 
二部グラフのパラメータ 
.PP
 \fBbipartite_matching\&.hpp\fP の \fB31\fP 行目に定義があります。
.SH "メンバ詳解"
.PP 
.SS "int BiInfo::max_matching"

.PP
最大マッチング 
.PP
 \fBbipartite_matching\&.hpp\fP の \fB32\fP 行目に定義があります。
.SS "int BiInfo::min_edge_cover"

.PP
最小辺被覆 
.PP
 \fBbipartite_matching\&.hpp\fP の \fB33\fP 行目に定義があります。
.SS "int BiInfo::max_independent_set"

.PP
最大独立集合 
.PP
 \fBbipartite_matching\&.hpp\fP の \fB34\fP 行目に定義があります。
.SS "int BiInfo::min_vertex_cover"
最小頂点被覆 
.PP
 \fBbipartite_matching\&.hpp\fP の \fB35\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
