.TH "others/bit.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
others/bit.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "名前空間"

.in +1c
.ti -1c
.RI "namespace \fBBit\fP"
.br
.RI "ビット演算 "
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "int \fBBit::PopCount\fP (int n)"
.br
.RI "1であるビットの個数を返す "
.ti -1c
.RI "int \fBBit::PopCount\fP (\fBll\fP n)"
.br
.RI "1であるビットの個数を返す "
.ti -1c
.RI "int \fBBit::Parity\fP (int n)"
.br
.RI "popcountの偶奇を返す "
.ti -1c
.RI "int \fBBit::Parity\fP (\fBll\fP n)"
.br
.RI "popcountの偶奇を返す "
.ti -1c
.RI "int \fBBit::TopBit\fP (int n)"
.br
.RI "最上位ビットの位置を返す "
.ti -1c
.RI "int \fBBit::TopBit\fP (\fBll\fP n)"
.br
.RI "最上位ビットの位置を返す "
.ti -1c
.RI "int \fBBit::BitLength\fP (int n)"
.br
.RI "2進表現の長さを返す "
.ti -1c
.RI "int \fBBit::BitLength\fP (\fBll\fP n)"
.br
.ti -1c
.RI "int \fBBit::LowBit\fP (int n)"
.br
.RI "最下位ビットの位置を返す "
.ti -1c
.RI "int \fBBit::LowBit\fP (\fBll\fP n)"
.br
.RI "最下位ビットの位置を返す "
.ti -1c
.RI "bool \fBBit::IsPowerOfTwo\fP (int n)"
.br
.RI "2のべき乗か否かを返す "
.ti -1c
.RI "\fBll\fP \fBBit::Mask\fP (int n)"
.br
.RI "0~n-1 ビットを立てたビットマスクを返す "
.ti -1c
.RI "bool \fBBit::HasBit\fP (\fBll\fP n, int i)"
.br
.RI "iビット目が立っているか否かを返す "
.ti -1c
.RI "string \fBBit::ToBinary\fP (\fBll\fP n, int len=32, bool rev=false)"
.br
.RI "整数　ｎ の2進表現を返す "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
