.TH "BridgeInfo" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BridgeInfo \- 橋と関節点の情報  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'lowlink\&.hpp'\fP
.SS "公開変数類"

.in +1c
.ti -1c
.RI "vector< pair< int, int > > \fBbridge\fP"
.br
.RI "橋 "
.ti -1c
.RI "\fBVI\fP \fBarticulation\fP"
.br
.RI "関節点 "
.in -1c
.SH "詳解"
.PP 
橋と関節点の情報 
.PP
 \fBlowlink\&.hpp\fP の \fB4\fP 行目に定義があります。
.SH "メンバ詳解"
.PP 
.SS "vector<pair<int,int> > BridgeInfo::bridge"

.PP
橋 
.PP
 \fBlowlink\&.hpp\fP の \fB5\fP 行目に定義があります。
.SS "\fBVI\fP BridgeInfo::articulation"

.PP
関節点 
.PP
 \fBlowlink\&.hpp\fP の \fB6\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
