.TH "graph/tree/centroid.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph/tree/centroid.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "int \fBTreeCentroid\fP (const \fBVVI\fP &g, int root, \fBVI\fP &seen, \fBVI\fP &sz)"
.br
.RI "重心分解 "
.in -1c
.SH "関数詳解"
.PP 
.SS "int TreeCentroid (const \fBVVI\fP & g, int root, \fBVI\fP & seen, \fBVI\fP & sz)"

.PP
重心分解 
.PP
\fB引数\fP
.RS 4
\fIseen\fP 探索済みフラグ 
.br
\fIsz\fP 各頂点の部分木のサイズ
.RE
.PP
.PP
.nf
vector<int> sz(N);
vector<bool> seen(N);

auto centroid_decomposition = [&](auto self, int root) \-> void {
    int centroid = TreeCentroid(g, root, seen, sz);
    seen[centroid] = true;

    // ここに処理を書く

    for (int nxt : g[centroid]) {
        if (seen[nxt]) continue;
        self(self, nxt);
    }
};
centroid_decomposition(centroid_decomposition, 0);
.fi
.PP
 
.PP
 \fBcentroid\&.hpp\fP の \fB27\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
