.TH "algorithm/cht.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
algorithm/cht.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./kyopro_library/algorithm/binary_search\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBCHT< T, Min >\fP"
.br
.RI "Convex Hull Trick \fBverify\fP : https://judge.yosupo.jp/problem/line_add_get_min \fBhttps://hcpc-hokudai.github.io/archive/algorithm_convex_hull_trick_001.pdf\fP "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
