.TH "CHT< T, MIN >" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CHT< T, MIN > \- Convex Hull Trick \fBverify\fP : https://judge.yosupo.jp/problem/line_add_get_min \fBhttps://hcpc-hokudai.github.io/archive/algorithm_convex_hull_trick_001.pdf\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'cht\&.hpp'\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBCHT\fP ()=default"
.br
.ti -1c
.RI "void \fBadd\fP (T a, T b)"
.br
.RI "直線 ax + b を追加する "
.ti -1c
.RI "T \fBget\fP (T x)"
.br
.RI "x に対する直線群の最小値を求める "
.in -1c
.SH "詳解"
.PP 

.SS "template<typename T = ll, bool MIN = true>
.br
struct CHT< T, MIN >"Convex Hull Trick \fBverify\fP : https://judge.yosupo.jp/problem/line_add_get_min \fBhttps://hcpc-hokudai.github.io/archive/algorithm_convex_hull_trick_001.pdf\fP 


.PP
\fBテンプレート引数\fP
.RS 4
\fIMin\fP true のとき最小値を管理する 
.RE
.PP

.PP
 \fBcht\&.hpp\fP の \fB9\fP 行目に定義があります。
.SH "構築子と解体子"
.PP 
.SS "template<typename T = ll, bool MIN = true> \fBCHT\fP< T, MIN >\fB::CHT\fP ()\fR [default]\fP"

.SH "関数詳解"
.PP 
.SS "template<typename T = ll, bool MIN = true> void \fBCHT\fP< T, MIN >::add (T a, T b)\fR [inline]\fP"

.PP
直線 ax + b を追加する 
.PP
\fB覚え書き\fP
.RS 4
O(log(N)) 
.RE
.PP

.PP
 \fBcht\&.hpp\fP の \fB14\fP 行目に定義があります。
.SS "template<typename T = ll, bool MIN = true> T \fBCHT\fP< T, MIN >::get (T x)\fR [inline]\fP"

.PP
x に対する直線群の最小値を求める 
.PP
\fB覚え書き\fP
.RS 4
O((log(N))^2) 
.RE
.PP

.PP
 \fBcht\&.hpp\fP の \fB46\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
