.TH "mod/combination_lucas.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mod/combination_lucas.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./kyopro_library/others/modcal\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBCombinationLucas\fP"
.br
.RI "Lucas の定理を用いた二項係数計算用ライブラリ "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
