.TH "kyopro_tools/compress.py" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kyopro_tools/compress.py
.SH SYNOPSIS
.br
.PP
.SS "名前空間"

.in +1c
.ti -1c
.RI "namespace \fBcompress\fP"
.br
.in -1c
.SS "変数"

.in +1c
.ti -1c
.RI "list \fBcompress\&.symbols\fP = ['!','#','$','%','&','*','+','\-','/','<','=','>','?','@','^','_','~','|','\\\\','\&.',':',';','[',']','{','}','(',')',''',''',',']"
.br
.ti -1c
.RI "str \fBcompress\&.code\fP = ''"
.br
.ti -1c
.RI "\fBcompress\&.line\fP = input()"
.br
.ti -1c
.RI "str \fBcompress\&.res\fP = ''"
.br
.ti -1c
.RI "str \fBcompress\&.a\fP = ' '+symbol"
.br
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
