.TH "compress" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
compress
.SH SYNOPSIS
.br
.PP
.SS "変数"

.in +1c
.ti -1c
.RI "list \fBsymbols\fP = ['!','#','$','%','&','*','+','\-','/','<','=','>','?','@','^','_','~','|','\\\\','\&.',':',';','[',']','{','}','(',')',''',''',',']"
.br
.ti -1c
.RI "str \fBcode\fP = ''"
.br
.ti -1c
.RI "\fBline\fP = input()"
.br
.ti -1c
.RI "str \fBres\fP = ''"
.br
.ti -1c
.RI "str \fBa\fP = ' '+symbol"
.br
.in -1c
.SH "変数詳解"
.PP 
.SS "list compress\&.symbols = ['!','#','$','%','&','*','+','\-','/','<','=','>','?','@','^','_','~','|','\\\\','\&.',':',';','[',']','{','}','(',')',''',''',',']"

.PP
 \fBcompress\&.py\fP の \fB1\fP 行目に定義があります。
.SS "str compress\&.code = ''"

.PP
 \fBcompress\&.py\fP の \fB3\fP 行目に定義があります。
.SS "compress\&.line = input()"

.PP
 \fBcompress\&.py\fP の \fB7\fP 行目に定義があります。
.SS "str compress\&.res = ''"

.PP
 \fBcompress\&.py\fP の \fB12\fP 行目に定義があります。
.SS "str compress\&.a = ' '+symbol"

.PP
 \fBcompress\&.py\fP の \fB17\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
