.TH "data_structure/cumulative_sum_2d.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_structure/cumulative_sum_2d.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBCumulativeSum2D< T >\fP"
.br
.RI "2次元累積和 "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
