.TH "CumulativeSum2D< T >" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CumulativeSum2D< T > \- 2次元累積和  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'cumulative_sum_2d\&.hpp'\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBCumulativeSum2D\fP ()=default"
.br
.ti -1c
.RI "template<typename U> \fBCumulativeSum2D\fP (const vector< vector< U > > &v)"
.br
.RI "v から2次元累積和を構築する "
.ti -1c
.RI "T \fBsum\fP (int l, int r, int u, int d)"
.br
.RI "矩形領域 [l, r) × [u, d) の和を求める "
.in -1c
.SH "詳解"
.PP 

.SS "template<typename T>
.br
struct CumulativeSum2D< T >"2次元累積和 


.PP
\fBテンプレート引数\fP
.RS 4
\fIT\fP 群 
.RE
.PP

.PP
 \fBcumulative_sum_2d\&.hpp\fP の \fB6\fP 行目に定義があります。
.SH "構築子と解体子"
.PP 
.SS "template<typename T> \fBCumulativeSum2D\fP< T >\fB::CumulativeSum2D\fP ()\fR [default]\fP"

.SS "template<typename T> template<typename U> \fBCumulativeSum2D\fP< T >\fB::CumulativeSum2D\fP (const vector< vector< U > > & v)\fR [inline]\fP"

.PP
v から2次元累積和を構築する 
.PP
 \fBcumulative_sum_2d\&.hpp\fP の \fB11\fP 行目に定義があります。
.SH "関数詳解"
.PP 
.SS "template<typename T> T \fBCumulativeSum2D\fP< T >::sum (int l, int r, int u, int d)\fR [inline]\fP"

.PP
矩形領域 [l, r) × [u, d) の和を求める 
.PP
 \fBcumulative_sum_2d\&.hpp\fP の \fB18\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
