.TH "graph/tree/diameter.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph/tree/diameter.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./\&.\&./kyopro_library/graph/shortest_path/dijkstra\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./\&.\&./kyopro_library/graph/shortest_path/bfs\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "pair< \fBVI\fP, \fBll\fP > \fBTreeDiameter\fP (const \fBWG\fP &g)"
.br
.ti -1c
.RI "pair< \fBVI\fP, \fBll\fP > \fBTreeDiameter\fP (const \fBVVI\fP &g)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "pair< \fBVI\fP, \fBll\fP > TreeDiameter (const \fBWG\fP & g)"

.PP
 \fBdiameter\&.hpp\fP の \fB5\fP 行目に定義があります。
.SS "pair< \fBVI\fP, \fBll\fP > TreeDiameter (const \fBVVI\fP & g)"

.PP
 \fBdiameter\&.hpp\fP の \fB26\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
