.TH "graph/shortest_path/dijkstra.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph/shortest_path/dijkstra.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "\fBVL\fP \fBDijkstra\fP (const \fBWG\fP &g, int start=0)"
.br
.RI "ダイクストラ法 "
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBVL\fP Dijkstra (const \fBWG\fP & g, int start = \fR0\fP)"

.PP
ダイクストラ法 グラフ g に対し、頂点 start から各頂点までの最短距離を求める 
.PP
\fB覚え書き\fP
.RS 4
O(E log V) 
.RE
.PP

.PP
 \fBdijkstra\&.hpp\fP の \fB6\fP 行目に定義があります。
.PP
参照先 \fBINFL\fP\&.
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
