.TH "Doubling< Log >" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Doubling< Log > \- ダブリング  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'doubling\&.hpp'\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBDoubling\fP ()=default"
.br
.ti -1c
.RI "\fBDoubling\fP (const \fBVI\fP &v)"
.br
.RI "コンストラクタ "
.ti -1c
.RI "int \fBnext\fP (int start, \fBll\fP k)"
.br
.RI "頂点 start から k 回遷移した先の頂点を返す "
.in -1c
.SH "詳解"
.PP 

.SS "template<int Log>
.br
struct Doubling< Log >"ダブリング 


.PP
\fB引数\fP
.RS 4
\fILog\fP ダブリングの深さ 
.RE
.PP

.PP
 \fBdoubling\&.hpp\fP の \fB6\fP 行目に定義があります。
.SH "構築子と解体子"
.PP 
.SS "template<int Log> \fBDoubling\fP< Log >\fB::Doubling\fP ()\fR [default]\fP"

.SS "template<int Log> \fBDoubling\fP< Log >\fB::Doubling\fP (const \fBVI\fP & v)\fR [inline]\fP"

.PP
コンストラクタ 
.PP
\fB引数\fP
.RS 4
\fIv\fP 各頂点からの遷移先 
.RE
.PP
\fB覚え書き\fP
.RS 4
O(N Log) 
.RE
.PP

.PP
 \fBdoubling\&.hpp\fP の \fB12\fP 行目に定義があります。
.SH "関数詳解"
.PP 
.SS "template<int Log> int \fBDoubling\fP< Log >::next (int start, \fBll\fP k)\fR [inline]\fP"

.PP
頂点 start から k 回遷移した先の頂点を返す 
.PP
\fB覚え書き\fP
.RS 4
O(Log) 
.RE
.PP

.PP
 \fBdoubling\&.hpp\fP の \fB22\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
