.TH "algorithm/doubling.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
algorithm/doubling.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBDoubling< Log >\fP"
.br
.RI "ダブリング "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
