.TH "graph/dsu_potentialized.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph/dsu_potentialized.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBDsuPotentialized< Group >\fP"
.br
.RI "ポテンシャル付き \fBDSU\fP "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
