.TH "DsuBaseSemigroup" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DsuBaseSemigroup
.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'dsu_merging\&.hpp'\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "using \fBType\fP = \fBll\fP"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBType\fP \fBop\fP (\fBType\fP a, \fBType\fP b)"
.br
.in -1c
.SH "詳解"
.PP 
 \fBdsu_merging\&.hpp\fP の \fB3\fP 行目に定義があります。
.SH "型定義メンバ詳解"
.PP 
.SS "using \fBDsuBaseSemigroup::Type\fP = \fBll\fP"

.PP
 \fBdsu_merging\&.hpp\fP の \fB4\fP 行目に定義があります。
.SH "関数詳解"
.PP 
.SS "static \fBType\fP DsuBaseSemigroup::op (\fBType\fP a, \fBType\fP b)\fR [inline]\fP, \fR [static]\fP"

.PP
 \fBdsu_merging\&.hpp\fP の \fB5\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
