.TH "DynamicConnectivity" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DynamicConnectivity \- オフラインのDinamic Connectivity  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'offline_dynamic_connectivity\&.hpp'\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBDynamicConnectivity\fP (int v, int q)"
.br
.RI "コンストラクタ "
.ti -1c
.RI "void \fBunite\fP (int time, int u, int v)"
.br
.RI "時間 time に頂点 u, v を連結する "
.ti -1c
.RI "void \fBcut\fP (int time, int u, int v)"
.br
.RI "時間 time に頂点 u, v を切断する "
.ti -1c
.RI "void \fBbuild\fP ()"
.br
.RI "クエリ処理の前計算を行う "
.ti -1c
.RI "void \fBexecute\fP (auto &f, int k=1)"
.br
.RI "クエリ関数 f を処理する "
.in -1c
.SH "詳解"
.PP 
オフラインのDinamic Connectivity 
.PP
 \fBoffline_dynamic_connectivity\&.hpp\fP の \fB5\fP 行目に定義があります。
.SH "構築子と解体子"
.PP 
.SS "DynamicConnectivity::DynamicConnectivity (int v, int q)\fR [inline]\fP"

.PP
コンストラクタ 
.PP
\fB引数\fP
.RS 4
\fIv\fP 頂点数 
.br
\fIq\fP クエリ数 
.RE
.PP

.PP
 \fBoffline_dynamic_connectivity\&.hpp\fP の \fB9\fP 行目に定義があります。
.SH "関数詳解"
.PP 
.SS "void DynamicConnectivity::unite (int time, int u, int v)\fR [inline]\fP"

.PP
時間 time に頂点 u, v を連結する 
.PP
 \fBoffline_dynamic_connectivity\&.hpp\fP の \fB16\fP 行目に定義があります。
.SS "void DynamicConnectivity::cut (int time, int u, int v)\fR [inline]\fP"

.PP
時間 time に頂点 u, v を切断する 
.PP
 \fBoffline_dynamic_connectivity\&.hpp\fP の \fB22\fP 行目に定義があります。
.SS "void DynamicConnectivity::build ()\fR [inline]\fP"

.PP
クエリ処理の前計算を行う 
.PP
 \fBoffline_dynamic_connectivity\&.hpp\fP の \fB28\fP 行目に定義があります。
.SS "void DynamicConnectivity::execute (auto & f, int k = \fR1\fP)\fR [inline]\fP"

.PP
クエリ関数 f を処理する 
.PP
 \fBoffline_dynamic_connectivity\&.hpp\fP の \fB42\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
