.TH "graph/tree/euler_tour.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph/tree/euler_tour.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "tuple< \fBVI\fP, \fBVI\fP, \fBVI\fP, \fBVI\fP > \fBEulerTour\fP (const \fBVVI\fP &g)"
.br
.RI "木 g をオイラーツアーする "
.in -1c
.SH "関数詳解"
.PP 
.SS "tuple< \fBVI\fP, \fBVI\fP, \fBVI\fP, \fBVI\fP > EulerTour (const \fBVVI\fP & g)"

.PP
木 g をオイラーツアーする \fR(行きがけ順, 深さ, 入力時刻, 出力時刻)\fP を返す

.PP
部分木のクエリを列のに対する区間クエリとして扱えるようになる

.PP
例えば、頂点 v の部分木はオイラーツアー後の列の区間 \fR[in[v], out[v])\fP に対応する 
.PP
 \fBeuler_tour\&.hpp\fP の \fB7\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
