.TH "kyopro_tools/exp.py" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kyopro_tools/exp.py
.SH SYNOPSIS
.br
.PP
.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBexp\&.Expander\fP"
.br
.RI "\fBExpander\fP class is responsible for expanding libraries in the source code\&. "
.in -1c
.SS "名前空間"

.in +1c
.ti -1c
.RI "namespace \fBexp\fP"
.br
.in -1c
.SS "変数"

.in +1c
.ti -1c
.RI "bool \fBexp\&.HEAD\fP = False"
.br
.ti -1c
.RI "bool \fBexp\&.CONST\fP = True"
.br
.ti -1c
.RI "\fBexp\&.logger\fP = getLogger(__name__)"
.br
.ti -1c
.RI "\fBexp\&.format\fP"
.br
.ti -1c
.RI "\fBexp\&.datefmt\fP"
.br
.ti -1c
.RI "\fBexp\&.level\fP"
.br
.ti -1c
.RI "\fBexp\&.parser\fP = argparse\&.ArgumentParser(description='Expander')"
.br
.ti -1c
.RI "\fBexp\&.help\fP"
.br
.ti -1c
.RI "\fBexp\&.action\fP"
.br
.ti -1c
.RI "\fBexp\&.opts\fP = parser\&.parse_args()"
.br
.ti -1c
.RI "list \fBexp\&.lib_paths\fP = []"
.br
.ti -1c
.RI "\fBexp\&.expander\fP = \fBExpander\fP(\fBlib_paths\fP)"
.br
.ti -1c
.RI "\fBexp\&.source\fP = open(opts\&.source)\&.read()"
.br
.ti -1c
.RI "\fBexp\&.output\fP = expander\&.expand(\fBsource\fP)"
.br
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
