.TH "math/factors.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math/factors.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBFactors\fP"
.br
.RI "エラトステネスの篩を利用した高速な素因数分解・約数列挙（Osa_k 法） \fBhttps://osak.jp/diary/diary_201310.html#20131017\fP \fBhttps://qiita.com/drken/items/3beb679e54266f20ab63\fP "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
