.TH "Geometry::Segment" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Geometry::Segment \- 線分  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'geo\&.hpp'\fP
.PP
\fBGeometry::Line\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBSegment\fP ()=default"
.br
.ti -1c
.RI "\fBLine\fP ()=default"
.br
.ti -1c
.RI "\fBLine\fP (const \fBPoint\fP &_a, const \fBPoint\fP &_b)"
.br
.ti -1c
.RI "\fBLine\fP (const \fBReal\fP &A, const \fBReal\fP &B, const \fBReal\fP &C)"
.br
.RI "直線 Ax+By=C を定義する "
.in -1c

基底クラス \fBGeometry::Line\fP に属する継承公開メンバ関数
.in +1c
.ti -1c
.RI "\fBLine\fP ()=default"
.br
.ti -1c
.RI "\fBLine\fP (const \fBPoint\fP &_a, const \fBPoint\fP &_b)"
.br
.ti -1c
.RI "\fBLine\fP (const \fBReal\fP &A, const \fBReal\fP &B, const \fBReal\fP &C)"
.br
.RI "直線 Ax+By=C を定義する "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBLine\fP &l) const"
.br
.in -1c
.SS "その他の継承メンバ"


基底クラス \fBGeometry::Line\fP に属する継承公開変数類
.in +1c
.ti -1c
.RI "\fBPoint\fP \fBa\fP"
.br
.ti -1c
.RI "\fBPoint\fP \fBb\fP"
.br
.in -1c
.SH "詳解"
.PP 
線分 
.PP
 \fBgeo\&.hpp\fP の \fB76\fP 行目に定義があります。
.SH "構築子と解体子"
.PP 
.SS "Geometry::Segment::Segment ()\fR [default]\fP"

.SH "関数詳解"
.PP 
.SS "Geometry::Line::Line ()\fR [default]\fP"

.SS "Geometry::Line::Line (const \fBPoint\fP & _a, const \fBPoint\fP & _b)\fR [inline]\fP"

.PP
 \fBgeo\&.hpp\fP の \fB51\fP 行目に定義があります。
.SS "Geometry::Line::Line (const \fBReal\fP & A, const \fBReal\fP & B, const \fBReal\fP & C)\fR [inline]\fP"

.PP
直線 Ax+By=C を定義する 
.PP
 \fBgeo\&.hpp\fP の \fB54\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
