.TH "Geometry::Line" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Geometry::Line
.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'geo\&.hpp'\fP
.PP
\fBGeometry::Segment\fPに継承されています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBLine\fP ()=default"
.br
.ti -1c
.RI "\fBLine\fP (const \fBPoint\fP &_a, const \fBPoint\fP &_b)"
.br
.ti -1c
.RI "\fBLine\fP (const \fBReal\fP &A, const \fBReal\fP &B, const \fBReal\fP &C)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBLine\fP &l) const"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBPoint\fP \fBa\fP"
.br
.ti -1c
.RI "\fBPoint\fP \fBb\fP"
.br
.in -1c
.SS "フレンド"

.in +1c
.ti -1c
.RI "istream & \fBoperator>>\fP (istream &is, \fBLine\fP &l)"
.br
.in -1c
.SH "詳解"
.PP 
 \fBgeo\&.hpp\fP の \fB31\fP 行目に定義があります。
.SH "構築子と解体子"
.PP 
.SS "Geometry::Line::Line ()\fR [default]\fP"

.SS "Geometry::Line::Line (const \fBPoint\fP & _a, const \fBPoint\fP & _b)\fR [inline]\fP"

.PP
 \fBgeo\&.hpp\fP の \fB34\fP 行目に定義があります。
.PP
参照先 \fBa\fP, \fBb\fP\&.
.SS "Geometry::Line::Line (const \fBReal\fP & A, const \fBReal\fP & B, const \fBReal\fP & C)\fR [inline]\fP"

.PP
 \fBgeo\&.hpp\fP の \fB36\fP 行目に定義があります。
.PP
参照先 \fBa\fP, \fBGeometry::almostEqual()\fP, \fBb\fP, \fBGeometry::Point::Point()\fP\&.
.SH "関数詳解"
.PP 
.SS "bool Geometry::Line::operator== (const \fBLine\fP & l) const\fR [inline]\fP"

.PP
 \fBgeo\&.hpp\fP の \fB52\fP 行目に定義があります。
.PP
参照先 \fBa\fP, \fBb\fP, \fBGeometry::Point::operator==()\fP\&.
.SH "フレンドと関連関数の詳解"
.PP 
.SS "istream & operator>> (istream & is, \fBLine\fP & l)\fR [friend]\fP"

.PP
 \fBgeo\&.hpp\fP の \fB53\fP 行目に定義があります。
.PP
参照先 \fBa\fP, \fBb\fP\&.
.SH "メンバ詳解"
.PP 
.SS "\fBPoint\fP Geometry::Line::a"

.PP
 \fBgeo\&.hpp\fP の \fB32\fP 行目に定義があります。
.SS "\fBPoint\fP Geometry::Line::b"

.PP
 \fBgeo\&.hpp\fP の \fB32\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
