.TH "Geometry::Circle" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Geometry::Circle \- 円  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'geo\&.hpp'\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBCircle\fP ()=default"
.br
.ti -1c
.RI "\fBCircle\fP (\fBReal\fP x, \fBReal\fP y, \fBReal\fP \fBr\fP)"
.br
.ti -1c
.RI "\fBCircle\fP (\fBPoint\fP _center, \fBReal\fP \fBr\fP)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCircle\fP &C) const"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBPoint\fP \fBcenter\fP"
.br
.RI "中心 "
.ti -1c
.RI "\fBReal\fP \fBr\fP"
.br
.RI "半径 "
.in -1c
.SS "フレンド"

.in +1c
.ti -1c
.RI "istream & \fBoperator>>\fP (istream &is, \fBCircle\fP &C)"
.br
.in -1c
.SH "詳解"
.PP 
円 
.PP
 \fBgeo\&.hpp\fP の \fB82\fP 行目に定義があります。
.SH "構築子と解体子"
.PP 
.SS "Geometry::Circle::Circle ()\fR [default]\fP"

.SS "Geometry::Circle::Circle (\fBReal\fP x, \fBReal\fP y, \fBReal\fP r)\fR [inline]\fP"

.PP
 \fBgeo\&.hpp\fP の \fB87\fP 行目に定義があります。
.PP
参照先 \fBcenter\fP, \fBGeometry::Point::Point()\fP, \fBr\fP\&.
.SS "Geometry::Circle::Circle (\fBPoint\fP _center, \fBReal\fP r)\fR [inline]\fP"

.PP
 \fBgeo\&.hpp\fP の \fB88\fP 行目に定義があります。
.PP
参照先 \fBcenter\fP, \fBr\fP\&.
.SH "関数詳解"
.PP 
.SS "bool Geometry::Circle::operator== (const \fBCircle\fP & C) const\fR [inline]\fP"

.PP
 \fBgeo\&.hpp\fP の \fB90\fP 行目に定義があります。
.PP
参照先 \fBcenter\fP, \fBGeometry::Point::operator==()\fP, \fBr\fP\&.
.SH "フレンドと関連関数の詳解"
.PP 
.SS "istream & operator>> (istream & is, \fBCircle\fP & C)\fR [friend]\fP"

.PP
 \fBgeo\&.hpp\fP の \fB91\fP 行目に定義があります。
.PP
参照先 \fBcenter\fP, \fBr\fP\&.
.SH "メンバ詳解"
.PP 
.SS "\fBPoint\fP Geometry::Circle::center"

.PP
中心 
.PP
 \fBgeo\&.hpp\fP の \fB83\fP 行目に定義があります。
.SS "\fBReal\fP Geometry::Circle::r"

.PP
半径 
.PP
 \fBgeo\&.hpp\fP の \fB84\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
