.TH "InsertableReversibleArrayImpl" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InsertableReversibleArrayImpl
.SH SYNOPSIS
.br
.PP
.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBLazyReversibleRBST\fP"
.br
.ti -1c
.RI "struct \fBLazyReversibleRBSTNode\fP"
.br
.ti -1c
.RI "struct \fBRBSTBase\fP"
.br
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "template<typename T> T \fBop\fP (T a, T b)"
.br
.ti -1c
.RI "template<typename T> T \fBe\fP (T a)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "template<typename T> T InsertableReversibleArrayImpl::op (T a, T b)"

.PP
 \fBinsert_reverse_array\&.hpp\fP の \fB143\fP 行目に定義があります。
.SS "template<typename T> T InsertableReversibleArrayImpl::e (T a)"

.PP
 \fBinsert_reverse_array\&.hpp\fP の \fB145\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
