.TH "data_structure/insert_reverse_array.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_structure/insert_reverse_array.hpp \- 挿入・削除・区間反転可能な配列 \fBhttps://nyaannyaan.github.io/library/rbst/lazy-reversible-rbst.hpp.html\fP  

.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBInsertableReversibleArrayImpl::RBSTBase< Node >\fP"
.br
.ti -1c
.RI "struct \fBInsertableReversibleArrayImpl::LazyReversibleRBSTNode< T, E >\fP"
.br
.ti -1c
.RI "struct \fBInsertableReversibleArrayImpl::LazyReversibleRBST< T, E, f, g, h, ts >\fP"
.br
.ti -1c
.RI "struct \fBInsertableReversibleArray< T >\fP"
.br
.in -1c
.SS "名前空間"

.in +1c
.ti -1c
.RI "namespace \fBInsertableReversibleArrayImpl\fP"
.br
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "template<typename T> T \fBInsertableReversibleArrayImpl::op\fP (T a, T b)"
.br
.ti -1c
.RI "template<typename T> T \fBInsertableReversibleArrayImpl::e\fP (T a)"
.br
.in -1c
.SH "詳解"
.PP 
挿入・削除・区間反転可能な配列 \fBhttps://nyaannyaan.github.io/library/rbst/lazy-reversible-rbst.hpp.html\fP 


.PP
 \fBinsert_reverse_array\&.hpp\fP に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
