.TH "others/int128.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
others/int128.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "constexpr \fBlll\fP \fBoperator''lll\fP (\fBull\fP x)"
.br
.ti -1c
.RI "istream & \fBoperator>>\fP (istream &is, \fBlll\fP &x)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, \fBlll\fP x)"
.br
.in -1c
.SS "変数"

.in +1c
.ti -1c
.RI "constexpr const \fBlll\fP \fBINFLL\fP =1\fBlll\fP<<120"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBlll\fP operator''lll (\fBull\fP x)\fR [constexpr]\fP"

.PP
 \fBint128\&.hpp\fP の \fB4\fP 行目に定義があります。
.SS "istream & operator>> (istream & is, \fBlll\fP & x)"

.PP
 \fBint128\&.hpp\fP の \fB7\fP 行目に定義があります。
.SS "ostream & operator<< (ostream & os, \fBlll\fP x)"

.PP
 \fBint128\&.hpp\fP の \fB18\fP 行目に定義があります。
.SH "変数詳解"
.PP 
.SS "const \fBlll\fP INFLL =1\fBlll\fP<<120\fR [constexpr]\fP"

.PP
 \fBint128\&.hpp\fP の \fB5\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
