.TH "others/int128.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
others/int128.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "istream & \fBoperator>>\fP (istream &is, \fBLL\fP &x)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, \fBLL\fP x)"
.br
.in -1c
.SS "変数"

.in +1c
.ti -1c
.RI "constexpr const \fBLL\fP \fBLL0\fP =0"
.br
.ti -1c
.RI "constexpr const \fBLL\fP \fBLL1\fP =1"
.br
.ti -1c
.RI "constexpr const \fBLL\fP \fBINFLL\fP =\fBLL1\fP<<120"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "istream & operator>> (istream & is, \fBLL\fP & x)"

.PP
 \fBint128\&.hpp\fP の \fB8\fP 行目に定義があります。
.SS "ostream & operator<< (ostream & os, \fBLL\fP x)"

.PP
 \fBint128\&.hpp\fP の \fB19\fP 行目に定義があります。
.SH "変数詳解"
.PP 
.SS "const \fBLL\fP LL0 =0\fR [constexpr]\fP"

.PP
 \fBint128\&.hpp\fP の \fB4\fP 行目に定義があります。
.SS "const \fBLL\fP LL1 =1\fR [constexpr]\fP"

.PP
 \fBint128\&.hpp\fP の \fB5\fP 行目に定義があります。
.SS "const \fBLL\fP INFLL =\fBLL1\fP<<120\fR [constexpr]\fP"

.PP
 \fBint128\&.hpp\fP の \fB6\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
