.TH "others/intersect.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
others/intersect.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "bool \fBHaveIntersection\fP (const \fBll\fP l1, const \fBll\fP r1, const \fBll\fP l2, const \fBll\fP r2)"
.br
.RI "区間 [l1, r1) と [l2, r2) が交差しているか否かを返す "
.in -1c
.SH "関数詳解"
.PP 
.SS "bool HaveIntersection (const \fBll\fP l1, const \fBll\fP r1, const \fBll\fP l2, const \fBll\fP r2)"

.PP
区間 [l1, r1) と [l2, r2) が交差しているか否かを返す 
.PP
 \fBintersect\&.hpp\fP の \fB4\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
