.TH "algorithm/inversion_number.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
algorithm/inversion_number.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "\fBll\fP \fBInversionNumber\fP (const \fBVI\fP &v)"
.br
.RI "転倒数 "
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBll\fP InversionNumber (const \fBVI\fP & v)"

.PP
転倒数 配列 v の転倒数を求める 
.PP
\fB覚え書き\fP
.RS 4
O(N log(N)) 
.RE
.PP

.PP
 \fBinversion_number\&.hpp\fP の \fB6\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
