.TH "others/kth_root.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
others/kth_root.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./kyopro_library/algorithm/binary_search\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "\fBll\fP \fBKthRoot\fP (\fBll\fP n, \fBll\fP k=2)"
.br
.RI "n　の k 乗根の切り捨てを返す "
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBll\fP KthRoot (\fBll\fP n, \fBll\fP k = \fR2\fP)"

.PP
n　の k 乗根の切り捨てを返す 
.PP
 \fBkth_root\&.hpp\fP の \fB5\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
