.TH "math/lagrange2.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math/lagrange2.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "template<typename T> vector< T > \fBlagrangePolynomial\fP (vector< T >x, vector< T >y)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "template<typename T> vector< T > lagrangePolynomial (vector< T > x, vector< T > y)"

.PP
 \fBlagrange2\&.hpp\fP の \fB6\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
