.TH "graph/tree/lca_edge.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph/tree/lca_edge.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./\&.\&./kyopro_library/others/monoid\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBLcaEdge< Monoid >\fP"
.br
.RI "辺属性LCA "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
