.TH "string/lcp_array.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
string/lcp_array.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./kyopro_library/string/suffix_array\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "\fBVI\fP \fBLcpArray\fP (const string &s, const \fBVI\fP &sa)"
.br
.RI "LCP Array "
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBVI\fP LcpArray (const string & s, const \fBVI\fP & sa)"

.PP
LCP Array \fRlcp[i] := sa[i] と sa[i-1] の lcp の長さ\fP \fBhttps://qiita.com/kgoto/items/9e28e37b8a4b15ea7230\fP 
.PP
 \fBlcp_array\&.hpp\fP の \fB8\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
