.TH "math/linear_equation.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math/linear_equation.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "int \fBRowReduction\fP (vector< vector< bool > > &a, \fBVI\fP &where)"
.br
.RI "F_2 上の連立線形方程式 \fBhttps://mathlandscape.com/solution-sp/\fP \fBhttps://yukicoder.me/submissions/1011997\fP \fBverify:https://yukicoder\&.me/problems/no/2895\fP "
.ti -1c
.RI "bool \fBLinearEquation\fP (vector< vector< bool > > a, vector< bool > b, vector< bool > &x0, vector< vector< bool > > &ker)"
.br
.RI "連立線形方程式 Ax=b を解く "
.in -1c
.SH "関数詳解"
.PP 
.SS "int RowReduction (vector< vector< bool > > & a, \fBVI\fP & where)"

.PP
F_2 上の連立線形方程式 \fBhttps://mathlandscape.com/solution-sp/\fP \fBhttps://yukicoder.me/submissions/1011997\fP \fBverify:https://yukicoder\&.me/problems/no/2895\fP 掃き出し法 
.PP
\fB引数\fP
.RS 4
\fIa\fP 連立方程式 Ax=b の拡大係数行列 
.br
\fIwhere\fP ピボットとなる変数を記録するための配列 
.RE
.PP
\fB戻り値\fP
.RS 4
A のランク 
.RE
.PP

.PP
 \fBlinear_equation\&.hpp\fP の \fB12\fP 行目に定義があります。
.SS "bool LinearEquation (vector< vector< bool > > a, vector< bool > b, vector< bool > & x0, vector< vector< bool > > & ker)"

.PP
連立線形方程式 Ax=b を解く 
.PP
\fB引数\fP
.RS 4
\fIx0\fP 特殊解(b=0 の場合は自明解になる) 
.br
\fIker\fP Ax=0 の解空間の基底 
.RE
.PP
\fB覚え書き\fP
.RS 4
一般解は x0 と解空間の基底の任意の線形結合で表される 
.RE
.PP
\fB注意\fP
.RS 4
A のサイズによっては基底のサイズが巨大になるので注意すること 
.RE
.PP

.PP
 \fBlinear_equation\&.hpp\fP の \fB37\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
