.TH "math/linear_programming_2vars.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math/linear_programming_2vars.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "\fBll\fP \fBLinearProgramming_2valiables\fP (\fBll\fP a, \fBll\fP b, \fBll\fP c, \fBll\fP p, \fBll\fP q)"
.br
.RI "2変数の線形計画問題 "
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBll\fP LinearProgramming_2valiables (\fBll\fP a, \fBll\fP b, \fBll\fP c, \fBll\fP p, \fBll\fP q)"

.PP
2変数の線形計画問題 ax + by >= c, x >= 0, y >= 0 という条件のもと、px+qy の最小値を返す 
.PP
\fB覚え書き\fP
.RS 4
O(sqrt(c)) 
.RE
.PP

.PP
 \fBlinear_programming_2vars\&.hpp\fP の \fB6\fP 行目に定義があります。
.PP
参照先 \fBINFL\fP\&.
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
