.TH "algorithm/lis.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
algorithm/lis.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "int \fBLisLength\fP (\fBVI\fP &v, bool strict=true)"
.br
.RI "LIS "
.in -1c
.SH "関数詳解"
.PP 
.SS "int LisLength (\fBVI\fP & v, bool strict = \fRtrue\fP)"

.PP
LIS 配列 v の最長増加部分列の長さを返す 
.PP
\fB引数\fP
.RS 4
\fIstrict\fP \fRtrue\fP のとき狭義単調増加 
.RE
.PP
\fB覚え書き\fP
.RS 4
O(N log(N)) 
.RE
.PP

.PP
 \fBlis\&.hpp\fP の \fB7\fP 行目に定義があります。
.PP
参照先 \fBINF\fP\&.
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
