.TH "graph/lowlink.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph/lowlink.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBBridgeInfo\fP"
.br
.RI "橋と関節点の情報 "
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "\fBBridgeInfo\fP \fBLowLink\fP (const \fBVVI\fP &g)"
.br
.RI "Low Link のアルゴリズムによりグラフGの橋と関節点を求める "
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBBridgeInfo\fP LowLink (const \fBVVI\fP & g)"

.PP
Low Link のアルゴリズムによりグラフGの橋と関節点を求める 
.PP
\fB覚え書き\fP
.RS 4
O(V+E) 
.RE
.PP

.PP
 \fBlowlink\&.hpp\fP の \fB11\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
