.TH "math/matrix.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math/matrix.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "template<typename T> vector< vector< T > > \fBMatMul\fP (const vector< vector< T > > &A, const vector< vector< T > > &B)"
.br
.ti -1c
.RI "template<typename T> vector< vector< T > > \fBMatPow\fP (vector< vector< T > > A, \fBll\fP b)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "template<typename T> vector< vector< T > > MatMul (const vector< vector< T > > & A, const vector< vector< T > > & B)"

.PP
 \fBmatrix\&.hpp\fP の \fB4\fP 行目に定義があります。
.SS "template<typename T> vector< vector< T > > MatPow (vector< vector< T > > A, \fBll\fP b)"

.PP
 \fBmatrix\&.hpp\fP の \fB12\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
