.TH "MaxFlow" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxFlow \- 最大流  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'max_flow\&.hpp'\fP
.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBEdge\fP"
.br
.RI "辺構造体 "
.in -1c
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBMaxFlow\fP (int n)"
.br
.ti -1c
.RI "void \fBadd_edge\fP (int from, int to, \fBll\fP cap)"
.br
.RI "容量 cap の辺を追加する "
.ti -1c
.RI "\fBll\fP \fBflow\fP (int s, int t)"
.br
.RI "s から t への最大流を求める "
.ti -1c
.RI "\fBVI\fP \fBmincut\fP (int v=0)"
.br
.RI "直前に流したフローから最小カットを復元する "
.ti -1c
.RI "vector< \fBEdge\fP > \fBget_edges\fP ()"
.br
.RI "直前に流したフローの辺の情報を返す "
.in -1c
.SH "詳解"
.PP 
最大流 
.PP
 \fBmax_flow\&.hpp\fP の \fB4\fP 行目に定義があります。
.SH "構築子と解体子"
.PP 
.SS "MaxFlow::MaxFlow (int n)\fR [inline]\fP"

.PP
 \fBmax_flow\&.hpp\fP の \fB16\fP 行目に定義があります。
.SH "関数詳解"
.PP 
.SS "void MaxFlow::add_edge (int from, int to, \fBll\fP cap)\fR [inline]\fP"

.PP
容量 cap の辺を追加する 
.PP
 \fBmax_flow\&.hpp\fP の \fB19\fP 行目に定義があります。
.SS "\fBll\fP MaxFlow::flow (int s, int t)\fR [inline]\fP"

.PP
s から t への最大流を求める 
.PP
\fB覚え書き\fP
.RS 4
O(V^2 E) 
.RE
.PP

.PP
 \fBmax_flow\&.hpp\fP の \fB62\fP 行目に定義があります。
.PP
参照先 \fBINFL\fP\&.
.SS "\fBVI\fP MaxFlow::mincut (int v = \fR0\fP)\fR [inline]\fP"

.PP
直前に流したフローから最小カットを復元する 始点 v から到達可能か否か 
.PP
 \fBmax_flow\&.hpp\fP の \fB75\fP 行目に定義があります。
.SS "vector< \fBEdge\fP > MaxFlow::get_edges ()\fR [inline]\fP"

.PP
直前に流したフローの辺の情報を返す 
.PP
 \fBmax_flow\&.hpp\fP の \fB94\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
