.TH "MaxFlow::Edge" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxFlow::Edge \- 辺構造体  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'max_flow\&.hpp'\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBEdge\fP (int \fBfrom\fP, int \fBto\fP, \fBll\fP \fBcap\fP, int \fBrev\fP, bool \fBisrev\fP)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "int \fBfrom\fP"
.br
.RI "始点 "
.ti -1c
.RI "int \fBto\fP"
.br
.RI "終点 "
.ti -1c
.RI "int \fBrev\fP"
.br
.RI "逆辺のインデックス "
.ti -1c
.RI "\fBll\fP \fBcap\fP"
.br
.RI "容量 "
.ti -1c
.RI "\fBll\fP \fBflow\fP"
.br
.RI "流量 "
.ti -1c
.RI "bool \fBisrev\fP"
.br
.in -1c
.SH "詳解"
.PP 
辺構造体 
.PP
 \fBmax_flow\&.hpp\fP の \fB6\fP 行目に定義があります。
.SH "構築子と解体子"
.PP 
.SS "MaxFlow::Edge::Edge (int from, int to, \fBll\fP cap, int rev, bool isrev)\fR [inline]\fP"

.PP
 \fBmax_flow\&.hpp\fP の \fB13\fP 行目に定義があります。
.PP
参照先 \fBcap\fP, \fBflow\fP, \fBfrom\fP, \fBisrev\fP, \fBrev\fP, \fBto\fP\&.
.SH "メンバ詳解"
.PP 
.SS "int MaxFlow::Edge::from"

.PP
始点 
.PP
 \fBmax_flow\&.hpp\fP の \fB7\fP 行目に定義があります。
.SS "int MaxFlow::Edge::to"

.PP
終点 
.PP
 \fBmax_flow\&.hpp\fP の \fB8\fP 行目に定義があります。
.SS "int MaxFlow::Edge::rev"

.PP
逆辺のインデックス 
.PP
 \fBmax_flow\&.hpp\fP の \fB9\fP 行目に定義があります。
.SS "\fBll\fP MaxFlow::Edge::cap"

.PP
容量 
.PP
 \fBmax_flow\&.hpp\fP の \fB10\fP 行目に定義があります。
.SS "\fBll\fP MaxFlow::Edge::flow"

.PP
流量 
.PP
 \fBmax_flow\&.hpp\fP の \fB11\fP 行目に定義があります。
.SS "bool MaxFlow::Edge::isrev"

.PP
 \fBmax_flow\&.hpp\fP の \fB12\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
