.TH "md_data__structure_2wvmt" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_data__structure_2wvmt \- wvmt 
.PP
\fBtop\fP
.SH "\fRWavelet Matrix\fP"
.PP
\fR解説\fP

.PP
\fR参考\fP

.PP
\fR原典\fP

.PP
全体集合のサイズを $\\sigma$ とする。

.PP
\fR\fBWaveletMatrix\fP(vector<ull> a)\fP

.PP
\fRull access(ull i)\fP
.IP "\(bu" 2
$a_i$ を復元する。
.IP "\(bu" 2
$O(\\log\\sigma)$
.PP

.PP
\fRull select(ull c, ull rank)\fP
.IP "\(bu" 2
$rank$ 番目の $c$ の位置 $+1$ を返す。 $rank$ は\fR1-indexed\fP。
.IP "\(bu" 2
$O(\\log\\sigma)$
.PP

.PP
\fRull max_range(ull l, ull r)\fP
.IP "\(bu" 2
$[l, r)$ で最大値のindexを返す。
.PP

.PP
\fRull min_range(ull l, ull r)\fP

.PP
\fRull quantile_range(ull l, ull r, ull k)\fP
.IP "\(bu" 2
$[l, r)$ で $k$ 番目に小さい数値のindexを返す。 $k$ は\fR0-indexed\fP。
.IP "\(bu" 2
$O(\\log\\sigma)$
.PP

.PP
\fRull rank(ull c, ull pos)\fP
.IP "\(bu" 2
$[0, pos)$ の $c$ の数。
.IP "\(bu" 2
$O(\\log\\sigma)$
.PP

.PP
\fRull range_freq(ull l, ull r, ull min, ull max)\fP
.IP "\(bu" 2
$[l, r)$ で $[min, max)$ に入る値の個数。
.IP "\(bu" 2
$O(\\log\\sigma)$
.PP

.PP
\fRull rank_less_than(ull c, ull l, ull r)\fP
.IP "\(bu" 2
$[l, r)$ で $c$ より小さい値の数。
.IP "\(bu" 2
$O(\\log\\sigma)$
.PP

.PP
\fRull rank_more_than(ull c, ull l, ull r)\fP

.PP
\fRtuple<ull, ull, ull> rank_all(ull c, ull l, ull r)\fP
.IP "\(bu" 2
$[l, r)$ で $($ $c$ と同じ値の数、$c$ より小さい値の数、$c$ より大きい値の数 $)$ 。
.IP "\(bu" 2
$O(\\log\\sigma)$
.PP

.PP
\fRpair<ull, ull> topk(ull l, ull r, ull k)\fP
.IP "\(bu" 2
$[l, r)$ で出現回数が多い順に $k$ 個の $($ 値, 頻度 $)$ を返す。頻度が同じ場合は小さいものが優先。
.IP "\(bu" 2
$O(k\\log\\sigma)$
.PP

.PP
\fRull range_sum(ull l, ull r, ull min, ull max)\fP
.IP "\(bu" 2
$[l, r)$ で $[min, max)$ に入る値の総和。
.IP "\(bu" 2
$O(\\log\\sigma)$
.PP

.PP
\fRull prev_value(ull l, ull r, ull min, ull max)\fP
.IP "\(bu" 2
$[l, r)$ で $[min, max)$ に入る値の最大値
.IP "\(bu" 2
$O(\\log\\sigma)$
.PP

.PP
\fRull next_value(ull l, ull r, ull min, ull max)\fP
.IP "\(bu" 2
$[l, r)$ で $[min, max)$ に入る値の最小値。
.IP "\(bu" 2
$O(\\log\\sigma)$
.PP

.PP
\fRtuple<ull, ull, ull> intersect(ull l1, ull r1, ull l2, ull r2)\fP
.IP "\(bu" 2
$[l1, r1)$, $[l2, r2)$ に共通して出現する要素を返す。(tupleの先頭)
.IP "\(bu" 2
$O(n)$ 
.PP

