.TH "Mo" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mo \- \fBMo\fP's Algorithm \fBhttps://ei1333.hateblo.jp/entry/2017/09/11/211011\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'mo\&.hpp'\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBMo\fP (int n)"
.br
.RI "コンストラクタ "
.ti -1c
.RI "void \fBadd\fP (int l, int r)"
.br
.RI "クエリ [l, r) を追加する "
.ti -1c
.RI "template<typename F1, typename F2, typename F3, typename F4, typename F5> void \fBexecute\fP (F1 &&add_left, F2 &&add_right, F3 &&del_left, F4 &&del_right, F5 &&out)"
.br
.RI "クエリを実行する "
.in -1c
.SH "詳解"
.PP 
\fBMo\fP's Algorithm \fBhttps://ei1333.hateblo.jp/entry/2017/09/11/211011\fP 
.PP
 \fBmo\&.hpp\fP の \fB5\fP 行目に定義があります。
.SH "構築子と解体子"
.PP 
.SS "Mo::Mo (int n)\fR [inline]\fP"

.PP
コンストラクタ 
.PP
 \fBmo\&.hpp\fP の \fB7\fP 行目に定義があります。
.SH "関数詳解"
.PP 
.SS "void Mo::add (int l, int r)\fR [inline]\fP"

.PP
クエリ [l, r) を追加する 
.PP
 \fBmo\&.hpp\fP の \fB13\fP 行目に定義があります。
.SS "template<typename F1, typename F2, typename F3, typename F4, typename F5> void Mo::execute (F1 && add_left, F2 && add_right, F3 && del_left, F4 && del_right, F5 && out)\fR [inline]\fP"

.PP
クエリを実行する 
.PP
\fB引数\fP
.RS 4
\fIadd_left\fP \fRadd_left(i)\fP i 番目の要素が左から加わるときの処理 
.br
\fIadd_right\fP \fRadd_right(i)\fP i 番目の要素が右から加わるときの処理 
.br
\fIdel_left\fP \fRdel_left(i)\fP i 番目の要素が左から抜けるときの処理 
.br
\fIdel_right\fP \fRdel_right(i)\fP i 番目の要素が右から抜けるときの処理 
.br
\fIout\fP \fRout(i)\fP i 番目のクエリの答えを求めたときの処理 
.RE
.PP
\fB覚え書き\fP
.RS 4
O(N sqrt(Q)) 
.RE
.PP

.PP
 \fBmo\&.hpp\fP の \fB27\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
