.TH "kyopro_tools/mod_reconstruct.py" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kyopro_tools/mod_reconstruct.py
.SH SYNOPSIS
.br
.PP
.SS "名前空間"

.in +1c
.ti -1c
.RI "namespace \fBmod_reconstruct\fP"
.br
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "\fBmod_reconstruct\&.reconstruct\fP (n, mod)"
.br
.ti -1c
.RI "\fBmod_reconstruct\&.add_rational_expression\fP (original, mod)"
.br
.ti -1c
.RI "\fBmod_reconstruct\&.main\fP ()"
.br
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
