.TH "mod_reconstruct" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mod_reconstruct
.SH SYNOPSIS
.br
.PP
.SS "関数"

.in +1c
.ti -1c
.RI "\fBreconstruct\fP (n, mod)"
.br
.ti -1c
.RI "\fBadd_rational_expression\fP (original, mod)"
.br
.ti -1c
.RI "\fBmain\fP ()"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "mod_reconstruct\&.reconstruct ( n,  mod)"

.PP
 \fBmod_reconstruct\&.py\fP の \fB3\fP 行目に定義があります。
.SS "mod_reconstruct\&.add_rational_expression ( original,  mod)"

.PP
 \fBmod_reconstruct\&.py\fP の \fB19\fP 行目に定義があります。
.PP
参照先 \fBreconstruct()\fP\&.
.SS "mod_reconstruct\&.main ()"

.PP
 \fBmod_reconstruct\&.py\fP の \fB50\fP 行目に定義があります。
.PP
参照先 \fBadd_rational_expression()\fP, \fBmain()\fP\&.
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
