.TH "others/modcal.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
others/modcal.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "template<typename T = ll> T \fBModPow\fP (T x, T n, T mod)"
.br
.RI "x^n (mod m) を返す "
.ti -1c
.RI "\fBll\fP \fBModInv\fP (\fBll\fP a, \fBll\fP m)"
.br
.RI "x^(-1) (mod m) を返す "
.in -1c
.SH "関数詳解"
.PP 
.SS "template<typename T = ll> T ModPow (T x, T n, T mod)"

.PP
x^n (mod m) を返す 
.PP
 \fBmodcal\&.hpp\fP の \fB6\fP 行目に定義があります。
.SS "\fBll\fP ModInv (\fBll\fP a, \fBll\fP m)"

.PP
x^(-1) (mod m) を返す 
.PP
 \fBmodcal\&.hpp\fP の \fB18\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
