.TH "mod/modint.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mod/modint.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBModInt< MOD >\fP"
.br
.RI "\fBModInt\fP "
.in -1c
.SS "型定義"

.in +1c
.ti -1c
.RI "using \fBMod998\fP = \fBModInt\fP<998244353>"
.br
.ti -1c
.RI "using \fBMod107\fP = \fBModInt\fP<1000000007>"
.br
.ti -1c
.RI "using \fBVM\fP = vector<\fBMod998\fP>"
.br
.in -1c
.SH "型定義詳解"
.PP 
.SS "using \fBMod998\fP = \fBModInt\fP<998244353>"

.PP
 \fBmodint\&.hpp\fP の \fB60\fP 行目に定義があります。
.SS "using \fBMod107\fP = \fBModInt\fP<1000000007>"

.PP
 \fBmodint\&.hpp\fP の \fB61\fP 行目に定義があります。
.SS "using \fBVM\fP = vector<\fBMod998\fP>"

.PP
 \fBmodint\&.hpp\fP の \fB62\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
