.TH "mod/modint_dynamic.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mod/modint_dynamic.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBDynamicModInt\fP"
.br
.RI "実行時に mod を変更できる \fBModInt\fP "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
