.TH "math/modlog.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math/modlog.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "\fBll\fP \fBModLog\fP (\fBll\fP x, \fBll\fP y, \fBll\fP mod)"
.br
.RI "離散対数問題 "
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBll\fP ModLog (\fBll\fP x, \fBll\fP y, \fBll\fP mod)"

.PP
離散対数問題 x^k=y mod m なる最小の k を返す 
.PP
\fB覚え書き\fP
.RS 4
O(sqrt(m)) 
.RE
.PP
\fB注意\fP
.RS 4
p は素数 
.RE
.PP

.PP
 \fBmodlog\&.hpp\fP の \fB7\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
