.TH "Monoid" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Monoid \- モノイド  

.SH SYNOPSIS
.br
.PP
.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBMax\fP"
.br
.RI "Maxモノイド "
.ti -1c
.RI "struct \fBMin\fP"
.br
.RI "Minモノイド "
.ti -1c
.RI "struct \fBSum\fP"
.br
.RI "和 "
.ti -1c
.RI "struct \fBSumPair\fP"
.br
.RI "（和，区間の長さ） "
.in -1c
.SH "詳解"
.PP 
モノイド 
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
