.TH "Monoid::Sum< T >" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Monoid::Sum< T > \- 和  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'monoid\&.hpp'\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "using \fBType\fP = T"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBType\fP \fBid\fP ()"
.br
.ti -1c
.RI "static \fBType\fP \fBop\fP (const \fBType\fP &a, const \fBType\fP &b)"
.br
.in -1c
.SH "詳解"
.PP 

.SS "template<typename T>
.br
struct Monoid::Sum< T >"和 
.PP
 \fBmonoid\&.hpp\fP の \fB26\fP 行目に定義があります。
.SH "型定義メンバ詳解"
.PP 
.SS "template<typename T> using \fBMonoid::Sum\fP< T >::Type = T"

.PP
 \fBmonoid\&.hpp\fP の \fB27\fP 行目に定義があります。
.SH "関数詳解"
.PP 
.SS "template<typename T> static \fBType\fP \fBMonoid::Sum\fP< T >::id ()\fR [inline]\fP, \fR [static]\fP"

.PP
 \fBmonoid\&.hpp\fP の \fB28\fP 行目に定義があります。
.SS "template<typename T> static \fBType\fP \fBMonoid::Sum\fP< T >::op (const \fBType\fP & a, const \fBType\fP & b)\fR [inline]\fP, \fR [static]\fP"

.PP
 \fBmonoid\&.hpp\fP の \fB29\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
