.TH "Monoid::Max< T, min_value >" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Monoid::Max< T, min_value > \- Maxモノイド  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'monoid\&.hpp'\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "using \fBType\fP = T"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBType\fP \fBid\fP ()"
.br
.ti -1c
.RI "static \fBType\fP \fBop\fP (const \fBType\fP &a, const \fBType\fP &b)"
.br
.in -1c
.SH "詳解"
.PP 

.SS "template<typename T, T min_value = \-INF>
.br
struct Monoid::Max< T, min_value >"Maxモノイド 


.PP
\fBテンプレート引数\fP
.RS 4
\fImin_value\fP 単位元 
.RE
.PP

.PP
 \fBmonoid\&.hpp\fP の \fB18\fP 行目に定義があります。
.SH "型定義メンバ詳解"
.PP 
.SS "template<typename T, T min_value = \-INF> using \fBMonoid::Max\fP< T, min_value >::Type = T"

.PP
 \fBmonoid\&.hpp\fP の \fB19\fP 行目に定義があります。
.SH "関数詳解"
.PP 
.SS "template<typename T, T min_value = \-INF> static \fBType\fP \fBMonoid::Max\fP< T, min_value >::id ()\fR [inline]\fP, \fR [static]\fP"

.PP
 \fBmonoid\&.hpp\fP の \fB20\fP 行目に定義があります。
.SS "template<typename T, T min_value = \-INF> static \fBType\fP \fBMonoid::Max\fP< T, min_value >::op (const \fBType\fP & a, const \fBType\fP & b)\fR [inline]\fP, \fR [static]\fP"

.PP
 \fBmonoid\&.hpp\fP の \fB21\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
