.TH "others/monoid.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
others/monoid.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBMonoid::Min< T, max_value >\fP"
.br
.RI "Minモノイド "
.ti -1c
.RI "struct \fBMonoid::Max< T, min_value >\fP"
.br
.RI "Maxモノイド "
.ti -1c
.RI "struct \fBMonoid::Sum< T >\fP"
.br
.RI "和 "
.ti -1c
.RI "struct \fBMonoid::SumPair< T >\fP"
.br
.RI "（和，区間の長さ） "
.in -1c
.SS "名前空間"

.in +1c
.ti -1c
.RI "namespace \fBMonoid\fP"
.br
.RI "モノイド "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
