.TH "graph/flow/moyasu_umeru.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph/flow/moyasu_umeru.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br
\fR#include <atcoder/maxflow>\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBBurningBurying< Cost >\fP"
.br
.RI "燃やす埋める "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
