.TH "NTT< MOD, primitive_root >" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTT< MOD, primitive_root > \- \fBNTT\fP Friendly 素数用 \fBNTT\fP 構造体  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'ntt\&.hpp'\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBNTT\fP ()"
.br
.ti -1c
.RI "\fBVL\fP \fBconvolve\fP (\fBVL\fP a, \fBVL\fP b)"
.br
.RI "a, b の畳み込み mod M を求める "
.in -1c
.SH "詳解"
.PP 

.SS "template<\fBll\fP MOD, \fBll\fP primitive_root>
.br
class NTT< MOD, primitive_root >"\fBNTT\fP Friendly 素数用 \fBNTT\fP 構造体 
.PP
 \fBntt\&.hpp\fP の \fB6\fP 行目に定義があります。
.SH "構築子と解体子"
.PP 
.SS "template<\fBll\fP MOD, \fBll\fP primitive_root> \fBNTT\fP< MOD, primitive_root >\fB::NTT\fP ()\fR [inline]\fP"

.PP
 \fBntt\&.hpp\fP の \fB31\fP 行目に定義があります。
.SH "関数詳解"
.PP 
.SS "template<\fBll\fP MOD, \fBll\fP primitive_root> \fBVL\fP \fBNTT\fP< MOD, primitive_root >::convolve (\fBVL\fP a, \fBVL\fP b)\fR [inline]\fP"

.PP
a, b の畳み込み mod M を求める 
.PP
 \fBntt\&.hpp\fP の \fB45\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
