.TH "math/ntt.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math/ntt.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./kyopro_library/others/modcal\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "class \fBNTT< MOD, primitive_root >\fP"
.br
.RI "\fBNTT\fP Friendly 素数用 \fBNTT\fP 構造体 "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
