.TH "graph/offline_dynamic_connectivity.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph/offline_dynamic_connectivity.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./kyopro_library/graph/dsu_rollback\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBDynamicConnectivity\fP"
.br
.RI "オフラインのDinamic Connectivity "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
