.TH "data_structure/offset_vector.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_structure/offset_vector.hpp \- 負の添字を取れる vector  

.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBOffsetVector< T >\fP"
.br
.in -1c
.SH "詳解"
.PP 
負の添字を取れる vector 


.PP
 \fBoffset_vector\&.hpp\fP に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
