.TH "Operator::Add< T >" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Operator::Add< T > \- 加算  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'operator\&.hpp'\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "using \fBType\fP = T"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBType\fP \fBid\fP ()"
.br
.ti -1c
.RI "static \fBType\fP \fBop\fP (const \fBType\fP &a, const \fBType\fP &b)"
.br
.in -1c
.SH "詳解"
.PP 

.SS "template<typename T>
.br
struct Operator::Add< T >"加算 
.PP
 \fBoperator\&.hpp\fP の \fB16\fP 行目に定義があります。
.SH "型定義メンバ詳解"
.PP 
.SS "template<typename T> using \fBOperator::Add\fP< T >::Type = T"

.PP
 \fBoperator\&.hpp\fP の \fB17\fP 行目に定義があります。
.SH "関数詳解"
.PP 
.SS "template<typename T> static \fBType\fP \fBOperator::Add\fP< T >::id ()\fR [inline]\fP, \fR [static]\fP"

.PP
 \fBoperator\&.hpp\fP の \fB18\fP 行目に定義があります。
.SS "template<typename T> static \fBType\fP \fBOperator::Add\fP< T >::op (const \fBType\fP & a, const \fBType\fP & b)\fR [inline]\fP, \fR [static]\fP"

.PP
 \fBoperator\&.hpp\fP の \fB19\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
