.TH "Operator::UpdateTimeStamp< T >" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Operator::UpdateTimeStamp< T > \- 可換な更新（タイムスタンプ）  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'operator\&.hpp'\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "using \fBType\fP = pair<T,int>"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBType\fP \fBid\fP ()"
.br
.ti -1c
.RI "static \fBType\fP \fBop\fP (const \fBType\fP &a, const \fBType\fP &b)"
.br
.in -1c
.SH "詳解"
.PP 

.SS "template<typename T>
.br
struct Operator::UpdateTimeStamp< T >"可換な更新（タイムスタンプ） 
.PP
 \fBoperator\&.hpp\fP の \fB24\fP 行目に定義があります。
.SH "型定義メンバ詳解"
.PP 
.SS "template<typename T> using \fBOperator::UpdateTimeStamp\fP< T >::Type = pair<T,int>"

.PP
 \fBoperator\&.hpp\fP の \fB25\fP 行目に定義があります。
.SH "関数詳解"
.PP 
.SS "template<typename T> static \fBType\fP \fBOperator::UpdateTimeStamp\fP< T >::id ()\fR [inline]\fP, \fR [static]\fP"

.PP
 \fBoperator\&.hpp\fP の \fB26\fP 行目に定義があります。
.SS "template<typename T> static \fBType\fP \fBOperator::UpdateTimeStamp\fP< T >::op (const \fBType\fP & a, const \fBType\fP & b)\fR [inline]\fP, \fR [static]\fP"

.PP
 \fBoperator\&.hpp\fP の \fB27\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
