.TH "Operator" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Operator \- 作用素  

.SH SYNOPSIS
.br
.PP
.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBAdd\fP"
.br
.RI "加算 "
.ti -1c
.RI "struct \fBUpdate\fP"
.br
.RI "更新 "
.ti -1c
.RI "struct \fBUpdateTimeStamp\fP"
.br
.RI "可換な更新（タイムスタンプ） "
.in -1c
.SH "詳解"
.PP 
作用素 
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
