.TH "Operator::Update< T, not_exist >" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Operator::Update< T, not_exist > \- 更新  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'operator\&.hpp'\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "using \fBType\fP = T"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static \fBType\fP \fBid\fP ()"
.br
.ti -1c
.RI "static \fBType\fP \fBop\fP (const \fBType\fP &a, const \fBType\fP &b)"
.br
.in -1c
.SH "詳解"
.PP 

.SS "template<typename T, T not_exist>
.br
struct Operator::Update< T, not_exist >"更新 
.PP
 \fBoperator\&.hpp\fP の \fB8\fP 行目に定義があります。
.SH "型定義メンバ詳解"
.PP 
.SS "template<typename T, T not_exist> using \fBOperator::Update\fP< T, not_exist >::Type = T"

.PP
 \fBoperator\&.hpp\fP の \fB9\fP 行目に定義があります。
.SH "関数詳解"
.PP 
.SS "template<typename T, T not_exist> static \fBType\fP \fBOperator::Update\fP< T, not_exist >::id ()\fR [inline]\fP, \fR [static]\fP"

.PP
 \fBoperator\&.hpp\fP の \fB10\fP 行目に定義があります。
.SS "template<typename T, T not_exist> static \fBType\fP \fBOperator::Update\fP< T, not_exist >::op (const \fBType\fP & a, const \fBType\fP & b)\fR [inline]\fP, \fR [static]\fP"

.PP
 \fBoperator\&.hpp\fP の \fB11\fP 行目に定義があります。
.PP
参照先 \fBid()\fP\&.

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
