.TH "math/primitive_root.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math/primitive_root.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./kyopro_library/others/modcal\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./kyopro_library/math/prime_factorize\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./kyopro_library/others/xor128\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "\fBll\fP \fBPrimitiveRoot\fP (\fBll\fP n)"
.br
.RI "n の原始根を求める \fBhttps://37zigen.com/primitive-root/\fP \fBverify:\fP https://judge.yosupo.jp/problem/primitive_root "
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBll\fP PrimitiveRoot (\fBll\fP n)"

.PP
n の原始根を求める \fBhttps://37zigen.com/primitive-root/\fP \fBverify:\fP https://judge.yosupo.jp/problem/primitive_root 
.PP
 \fBprimitive_root\&.hpp\fP の \fB10\fP 行目に定義があります。
.PP
参照先 \fBPrimalityTest()\fP, \fBXor128()\fP\&.
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
