.TH "math/prime_factorize.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math/prime_factorize.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./kyopro_library/math/primality_test\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "\fBVP\fP \fBPrimeFactorize\fP (\fBll\fP n)"
.br
.RI "ポラードのロー法で n を素因数分解する "
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBVP\fP PrimeFactorize (\fBll\fP n)"

.PP
ポラードのロー法で n を素因数分解する 
.PP
\fB覚え書き\fP
.RS 4
O(N^(1/4)) \fBhttps://qiita.com/t_fuki/items/7cd50de54d3c5d063b4a\fP \fBverify:\fP https://algo-method.com/tasks/553 
.RE
.PP

.PP
 \fBprime_factorize\&.hpp\fP の \fB8\fP 行目に定義があります。
.PP
参照先 \fBPrimalityTest()\fP\&.
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
