.TH "others/random.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
others/random.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./kyopro_library/others/xor128\&.hpp'\fP
.br

.SS "名前空間"

.in +1c
.ti -1c
.RI "namespace \fBRandomGenerator\fP"
.br
.RI "ランダムテストケース生成 "
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "template<typename T> T \fBRandomGenerator::RandomInt\fP (T n)"
.br
.RI "0 以上 n 未満のランダムな整数を返す "
.ti -1c
.RI "template<typename T> T \fBRandomGenerator::RandomInt\fP (T l, T r)"
.br
.RI "[l, r) の範囲からランダムな整数を返す "
.ti -1c
.RI "template<typename T> T \fBRandomGenerator::GetRandomElement\fP (vector< T > &a)"
.br
.RI "配列 a からランダムな要素を取得し、削除する "
.ti -1c
.RI "template<typename T> vector< T > \fBRandomGenerator::RandomArray\fP (int n, T lo, T hi, bool no_dup=false)"
.br
.RI "長さ n の [lo, hi) の要素からなるランダムな数列を返す "
.ti -1c
.RI "string \fBRandomGenerator::RandomAlphabet\fP (int n, bool lower=true)"
.br
.RI "ランダムなアルファベット文字列を返す "
.ti -1c
.RI "string \fBRandomGenerator::RandomString\fP (int n, string s)"
.br
.RI "文字列 s の要素からなるランダムな文字列を返す "
.ti -1c
.RI "template<typename T> vector< vector< T > > \fBRandomGenerator::RandomArray2D\fP (int \fBh\fP, int \fBw\fP, T lo, T hi)"
.br
.ti -1c
.RI "vector< string > \fBRandomGenerator::RandomAlphabet2D\fP (int \fBh\fP, int \fBw\fP, bool lower=true)"
.br
.ti -1c
.RI "vector< pair< int, int > > \fBRandomGenerator::RandomTree\fP (int n)"
.br
.ti -1c
.RI "vector< pair< int, int > > \fBRandomGenerator::RandomBinaryTree\fP (int n)"
.br
.ti -1c
.RI "vector< pair< int, int > > \fBRandomGenerator::RandomUndirectedGraph\fP (int n, int m, bool connected=true)"
.br
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
