.TH "RangeQuery" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RangeQuery \- 区間クエリ  

.SH SYNOPSIS
.br
.PP
.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBApplyAdd_GetMax\fP"
.br
.RI "区間加算 / 区間max "
.ti -1c
.RI "struct \fBApplyAdd_GetMin\fP"
.br
.RI "区間加算 / 区間min "
.ti -1c
.RI "struct \fBApplyAdd_GetSum\fP"
.br
.RI "区間加算 / 区間和 "
.ti -1c
.RI "struct \fBApplyUpdate_GetMax\fP"
.br
.RI "区間更新 / 区間max "
.ti -1c
.RI "struct \fBApplyUpdate_GetMin\fP"
.br
.RI "区間更新 / 区間min "
.ti -1c
.RI "struct \fBApplyUpdate_GetSum\fP"
.br
.RI "区間更新 / 区間和 "
.ti -1c
.RI "struct \fBMax\fP"
.br
.RI "1点変更 / 区間 max "
.ti -1c
.RI "struct \fBMaxDynamic\fP"
.br
.RI "1点変更 / 区間 max "
.ti -1c
.RI "struct \fBMin\fP"
.br
.RI "1点変更 / 区間 min "
.ti -1c
.RI "struct \fBMinDynamic\fP"
.br
.RI "1点変更 / 区間 min "
.ti -1c
.RI "struct \fBRangeAdd\fP"
.br
.ti -1c
.RI "struct \fBRangeUpdate\fP"
.br
.ti -1c
.RI "struct \fBSum\fP"
.br
.RI "1点変更 / 区間和 "
.ti -1c
.RI "struct \fBSumDynamic\fP"
.br
.RI "1点変更 / 区間和 "
.in -1c
.SH "詳解"
.PP 
区間クエリ 
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
