.TH "algorithm/range_arithmetic_add.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
algorithm/range_arithmetic_add.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "\fBVL\fP \fBRangeArithmeticAdd\fP (int n, vector< tuple< \fBll\fP, \fBll\fP, \fBll\fP, \fBll\fP > > query)"
.br
.RI "区間等差数列加算（オフライン） "
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBVL\fP RangeArithmeticAdd (int n, vector< tuple< \fBll\fP, \fBll\fP, \fBll\fP, \fBll\fP > > query)"

.PP
区間等差数列加算（オフライン） 長さ n の数列に対する区間等差数列加算クエリを処理する

.PP
クエリは \fR(l, r, start, step)\fP の形式で与える 
.PP
\fB覚え書き\fP
.RS 4
O(N) \fBverify:\fP https://mojacoder.app/users/Today03/problems/range_arithmetic_add \fBverify:\fP https://atcoder.jp/contests/abc407/tasks/abc407_f 
.RE
.PP

.PP
 \fBrange_arithmetic_add\&.hpp\fP の \fB9\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
