.TH "RangeQuery::SumDynamic< T >" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RangeQuery::SumDynamic< T > \- 1点変更 / 区間和  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'segtree_dynamic\&.hpp'\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "using \fBType\fP = struct \fBSegTreeDynamic\fP<\fBMonoid::Sum\fP<T>>"
.br
.in -1c
.SH "詳解"
.PP 

.SS "template<typename T>
.br
struct RangeQuery::SumDynamic< T >"1点変更 / 区間和 
.PP
 \fBsegtree_dynamic\&.hpp\fP の \fB101\fP 行目に定義があります。
.SH "型定義メンバ詳解"
.PP 
.SS "template<typename T> using \fBRangeQuery::SumDynamic\fP< T >::Type = struct \fBSegTreeDynamic\fP<\fBMonoid::Sum\fP<T>>"

.PP
 \fBsegtree_dynamic\&.hpp\fP の \fB101\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
