.TH "RangeQuery::MaxDynamic< T, min_value >" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RangeQuery::MaxDynamic< T, min_value > \- 1点変更 / 区間 max  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'segtree_dynamic\&.hpp'\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "using \fBType\fP = struct \fBSegTreeDynamic\fP<\fBMonoid::Max\fP<T,min_value>>"
.br
.in -1c
.SH "詳解"
.PP 

.SS "template<typename T, T min_value = \-INF>
.br
struct RangeQuery::MaxDynamic< T, min_value >"1点変更 / 区間 max 
.PP
 \fBsegtree_dynamic\&.hpp\fP の \fB97\fP 行目に定義があります。
.SH "型定義メンバ詳解"
.PP 
.SS "template<typename T, T min_value = \-INF> using \fBRangeQuery::MaxDynamic\fP< T, min_value >::Type = struct \fBSegTreeDynamic\fP<\fBMonoid::Max\fP<T,min_value>>"

.PP
 \fBsegtree_dynamic\&.hpp\fP の \fB97\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
