.TH "RangeQuery::MinDynamic< T, max_value >" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RangeQuery::MinDynamic< T, max_value > \- 1点変更 / 区間 min  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'segtree_dynamic\&.hpp'\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "using \fBType\fP = struct \fBSegTreeDynamic\fP<\fBMonoid::Min\fP<T,max_value>>"
.br
.in -1c
.SH "詳解"
.PP 

.SS "template<typename T, T max_value = INF>
.br
struct RangeQuery::MinDynamic< T, max_value >"1点変更 / 区間 min 
.PP
 \fBsegtree_dynamic\&.hpp\fP の \fB93\fP 行目に定義があります。
.SH "型定義メンバ詳解"
.PP 
.SS "template<typename T, T max_value = INF> using \fBRangeQuery::MinDynamic\fP< T, max_value >::Type = struct \fBSegTreeDynamic\fP<\fBMonoid::Min\fP<T,max_value>>"

.PP
 \fBsegtree_dynamic\&.hpp\fP の \fB93\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
