.TH "RangeQuery::ApplyUpdate_GetMax< T, min_value, not_exist >" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RangeQuery::ApplyUpdate_GetMax< T, min_value, not_exist > \- 区間更新 / 区間max  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'segtree_lazy\&.hpp'\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "using \fBType\fP = struct \fBSegTreeLazy\fP<\fBMonoid::Max\fP<T,min_value>,\fBOperator::Update\fP<T,not_exist>,\fBmapping\fP>"
.br
.in -1c
.SS "静的公開メンバ関数"

.in +1c
.ti -1c
.RI "static T \fBmapping\fP (const T &a, const T &b)"
.br
.in -1c
.SH "詳解"
.PP 

.SS "template<typename T, T min_value, T not_exist>
.br
struct RangeQuery::ApplyUpdate_GetMax< T, min_value, not_exist >"区間更新 / 区間max 


.PP
\fBテンプレート引数\fP
.RS 4
\fImin_value\fP 最小値 
.br
\fInot_exist\fP 存在しない値 
.RE
.PP

.PP
 \fBsegtree_lazy\&.hpp\fP の \fB216\fP 行目に定義があります。
.SH "型定義メンバ詳解"
.PP 
.SS "template<typename T, T min_value, T not_exist> using \fBRangeQuery::ApplyUpdate_GetMax\fP< T, min_value, not_exist >::Type = struct \fBSegTreeLazy\fP<\fBMonoid::Max\fP<T,min_value>,\fBOperator::Update\fP<T,not_exist>,\fBmapping\fP>"

.PP
 \fBsegtree_lazy\&.hpp\fP の \fB218\fP 行目に定義があります。
.SH "関数詳解"
.PP 
.SS "template<typename T, T min_value, T not_exist> static T \fBRangeQuery::ApplyUpdate_GetMax\fP< T, min_value, not_exist >::mapping (const T & a, const T & b)\fR [inline]\fP, \fR [static]\fP"

.PP
 \fBsegtree_lazy\&.hpp\fP の \fB217\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
