.TH "string/rolling_hash.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
string/rolling_hash.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./kyopro_library/others/xor128\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./kyopro_library/others/modcal\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBHash\fP"
.br
.ti -1c
.RI "struct \fBRollingHash\fP"
.br
.RI "Rolling \fBHash\fP "
.in -1c
.SS "変数"

.in +1c
.ti -1c
.RI "constexpr const int \fBHASH_MAX\fP =1000000"
.br
.ti -1c
.RI "constexpr const int \fBHASH_C\fP =256"
.br
.in -1c
.SH "変数詳解"
.PP 
.SS "const int HASH_MAX =1000000\fR [constexpr]\fP"

.PP
 \fBrolling_hash\&.hpp\fP の \fB5\fP 行目に定義があります。
.SS "const int HASH_C =256\fR [constexpr]\fP"

.PP
 \fBrolling_hash\&.hpp\fP の \fB6\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
