.TH "string/run_length_encoding.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
string/run_length_encoding.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "vector< pair< char, int > > \fBRunLengthEncoding\fP (const string &s)"
.br
.ti -1c
.RI "vector< pair< \fBll\fP, int > > \fBRunLengthEncoding\fP (const vector< \fBll\fP > &s)"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "vector< pair< char, int > > RunLengthEncoding (const string & s)"

.PP
 \fBrun_length_encoding\&.hpp\fP の \fB3\fP 行目に定義があります。
.SS "vector< pair< \fBll\fP, int > > RunLengthEncoding (const vector< \fBll\fP > & s)"

.PP
 \fBrun_length_encoding\&.hpp\fP の \fB15\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
