.TH "SccInfo" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SccInfo \- 強連結成分分解の情報  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'scc\&.hpp'\fP
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBVVI\fP \fBmembers\fP"
.br
.RI "各強連結成分の頂点 "
.ti -1c
.RI "\fBVVI\fP \fBgraph_decomposed\fP"
.br
.RI "強連結成分による分解グラフ "
.ti -1c
.RI "\fBVI\fP \fBgroup\fP"
.br
.RI "各頂点の所属する強連結成分の番号 "
.in -1c
.SH "詳解"
.PP 
強連結成分分解の情報 
.PP
 \fBscc\&.hpp\fP の \fB5\fP 行目に定義があります。
.SH "メンバ詳解"
.PP 
.SS "\fBVVI\fP SccInfo::members"

.PP
各強連結成分の頂点 
.PP
 \fBscc\&.hpp\fP の \fB6\fP 行目に定義があります。
.SS "\fBVVI\fP SccInfo::graph_decomposed"

.PP
強連結成分による分解グラフ 
.PP
 \fBscc\&.hpp\fP の \fB7\fP 行目に定義があります。
.SS "\fBVI\fP SccInfo::group"

.PP
各頂点の所属する強連結成分の番号 
.PP
 \fBscc\&.hpp\fP の \fB8\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
