.TH "SegTreeDynamic< Monoid >::Node" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SegTreeDynamic< Monoid >::Node
.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'segtree_dynamic\&.hpp'\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBNode\fP (\fBll\fP l, \fBll\fP r)"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "\fBType\fP \fBvalue\fP"
.br
.ti -1c
.RI "array< int, 2 > \fBto\fP"
.br
.ti -1c
.RI "\fBll\fP \fBleft\fP"
.br
.ti -1c
.RI "\fBll\fP \fBright\fP"
.br
.in -1c
.SH "詳解"
.PP 

.SS "template<typename Monoid>
.br
struct SegTreeDynamic< Monoid >::Node"
.PP
 \fBsegtree_dynamic\&.hpp\fP の \fB7\fP 行目に定義があります。
.SH "構築子と解体子"
.PP 
.SS "template<typename Monoid> \fBSegTreeDynamic\fP< Monoid >::Node::Node (\fBll\fP l, \fBll\fP r)\fR [inline]\fP"

.PP
 \fBsegtree_dynamic\&.hpp\fP の \fB11\fP 行目に定義があります。
.PP
参照先 \fBleft\fP, \fBright\fP, \fBvalue\fP\&.
.SH "メンバ詳解"
.PP 
.SS "template<typename Monoid> \fBType\fP \fBSegTreeDynamic\fP< Monoid >::Node::value"

.PP
 \fBsegtree_dynamic\&.hpp\fP の \fB8\fP 行目に定義があります。
.SS "template<typename Monoid> array<int,2> \fBSegTreeDynamic\fP< Monoid >::Node::to"

.PP
 \fBsegtree_dynamic\&.hpp\fP の \fB9\fP 行目に定義があります。
.SS "template<typename Monoid> \fBll\fP \fBSegTreeDynamic\fP< Monoid >::Node::left"

.PP
 \fBsegtree_dynamic\&.hpp\fP の \fB10\fP 行目に定義があります。
.SS "template<typename Monoid> \fBll\fP \fBSegTreeDynamic\fP< Monoid >::Node::right"

.PP
 \fBsegtree_dynamic\&.hpp\fP の \fB10\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
