.TH "data_structure/segtree_dual.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_structure/segtree_dual.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./kyopro_library/others/operator\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBSegTreeDual< CommutativeOperator >\fP"
.br
.RI "双対セグメント木 "
.ti -1c
.RI "struct \fBRangeQuery::RangeAdd< T >\fP"
.br
.ti -1c
.RI "struct \fBRangeQuery::RangeUpdate< T >\fP"
.br
.in -1c
.SS "名前空間"

.in +1c
.ti -1c
.RI "namespace \fBRangeQuery\fP"
.br
.RI "区間クエリ "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
