.TH "data_structure/segtree_dynamic.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_structure/segtree_dynamic.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./kyopro_library/others/monoid\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBSegTreeDynamic< Monoid >\fP"
.br
.RI "動的セグ木 "
.ti -1c
.RI "struct \fBSegTreeDynamic< Monoid >::Node\fP"
.br
.ti -1c
.RI "struct \fBRangeQuery::MinDynamic< T, max_value >\fP"
.br
.RI "1点変更 / 区間 min "
.ti -1c
.RI "struct \fBRangeQuery::MaxDynamic< T, min_value >\fP"
.br
.RI "1点変更 / 区間 max "
.ti -1c
.RI "struct \fBRangeQuery::SumDynamic< T >\fP"
.br
.RI "1点変更 / 区間和 "
.in -1c
.SS "名前空間"

.in +1c
.ti -1c
.RI "namespace \fBRangeQuery\fP"
.br
.RI "区間クエリ "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
