.TH "Set< T >" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Set< T > \- std::set ラッパー  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'set\&.hpp'\fP
.PP
set< T >を継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBSet\fP ()=default"
.br
.ti -1c
.RI "\fBSet\fP (T \fBnot_found\fP=\-1)"
.br
.RI "コンストラクタ "
.ti -1c
.RI "T \fBmin\fP ()"
.br
.RI "最小値を返す "
.ti -1c
.RI "T \fBmax\fP ()"
.br
.RI "最大値を返す "
.ti -1c
.RI "T \fBpop_min\fP ()"
.br
.RI "最小値を返し、削除する "
.ti -1c
.RI "T \fBpop_max\fP ()"
.br
.RI "最大値を返し、削除する "
.ti -1c
.RI "bool \fBcontains\fP (T x)"
.br
.RI "x が含まれているか否かを返す "
.ti -1c
.RI "bool \fBdiscard\fP (T x)"
.br
.RI "x を削除する "
.ti -1c
.RI "T \fBgt\fP (T x)"
.br
.RI "x より大きい最小の値を返す "
.ti -1c
.RI "T \fBge\fP (T x)"
.br
.RI "x 以上の最小の値を返す "
.ti -1c
.RI "T \fBle\fP (T x)"
.br
.RI "x 以下の最大の値を返す "
.ti -1c
.RI "T \fBlt\fP (T x)"
.br
.RI "x 未満の最大値の値を返す "
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "T \fBnot_found\fP"
.br
.in -1c
.SH "詳解"
.PP 

.SS "template<typename T>
.br
struct Set< T >"std::set ラッパー 
.PP
 \fBset\&.hpp\fP の \fB5\fP 行目に定義があります。
.SH "構築子と解体子"
.PP 
.SS "template<typename T> \fBSet\fP< T >\fB::Set\fP ()\fR [default]\fP"

.SS "template<typename T> \fBSet\fP< T >\fB::Set\fP (T not_found = \fR\-1\fP)\fR [inline]\fP"

.PP
コンストラクタ 
.PP
\fB引数\fP
.RS 4
\fInot_found\fP 指定の値が見つからなかったときに返す値 
.RE
.PP

.PP
 \fBset\&.hpp\fP の \fB12\fP 行目に定義があります。
.PP
参照先 \fBnot_found\fP\&.
.SH "関数詳解"
.PP 
.SS "template<typename T> T \fBSet\fP< T >::min ()\fR [inline]\fP"

.PP
最小値を返す 
.PP
 \fBset\&.hpp\fP の \fB15\fP 行目に定義があります。
.PP
参照先 \fBnot_found\fP\&.
.SS "template<typename T> T \fBSet\fP< T >::max ()\fR [inline]\fP"

.PP
最大値を返す 
.PP
 \fBset\&.hpp\fP の \fB21\fP 行目に定義があります。
.PP
参照先 \fBnot_found\fP\&.
.SS "template<typename T> T \fBSet\fP< T >::pop_min ()\fR [inline]\fP"

.PP
最小値を返し、削除する 
.PP
 \fBset\&.hpp\fP の \fB27\fP 行目に定義があります。
.PP
参照先 \fBmin()\fP, \fBnot_found\fP\&.
.SS "template<typename T> T \fBSet\fP< T >::pop_max ()\fR [inline]\fP"

.PP
最大値を返し、削除する 
.PP
 \fBset\&.hpp\fP の \fB35\fP 行目に定義があります。
.PP
参照先 \fBmax()\fP, \fBnot_found\fP\&.
.SS "template<typename T> bool \fBSet\fP< T >::contains (T x)\fR [inline]\fP"

.PP
x が含まれているか否かを返す 
.PP
 \fBset\&.hpp\fP の \fB43\fP 行目に定義があります。
.SS "template<typename T> bool \fBSet\fP< T >::discard (T x)\fR [inline]\fP"

.PP
x を削除する x が含まれていたか否かを返す 
.PP
 \fBset\&.hpp\fP の \fB49\fP 行目に定義があります。
.SS "template<typename T> T \fBSet\fP< T >::gt (T x)\fR [inline]\fP"

.PP
x より大きい最小の値を返す 
.PP
 \fBset\&.hpp\fP の \fB57\fP 行目に定義があります。
.PP
参照先 \fBnot_found\fP\&.
.SS "template<typename T> T \fBSet\fP< T >::ge (T x)\fR [inline]\fP"

.PP
x 以上の最小の値を返す 
.PP
 \fBset\&.hpp\fP の \fB64\fP 行目に定義があります。
.PP
参照先 \fBnot_found\fP\&.
.SS "template<typename T> T \fBSet\fP< T >::le (T x)\fR [inline]\fP"

.PP
x 以下の最大の値を返す 
.PP
 \fBset\&.hpp\fP の \fB71\fP 行目に定義があります。
.PP
参照先 \fBnot_found\fP\&.
.SS "template<typename T> T \fBSet\fP< T >::lt (T x)\fR [inline]\fP"

.PP
x 未満の最大値の値を返す 
.PP
 \fBset\&.hpp\fP の \fB78\fP 行目に定義があります。
.PP
参照先 \fBnot_found\fP\&.
.SH "メンバ詳解"
.PP 
.SS "template<typename T> T \fBSet\fP< T >::not_found"

.PP
 \fBset\&.hpp\fP の \fB7\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
