.TH "SortedTree< T >" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SortedTree< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'sorted_tree\&.hpp'\fP
.PP
tree< T, null_type, less< T >, rb_tree_tag, tree_order_statistics_node_update >を継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBSortedTree\fP ()=default"
.br
.ti -1c
.RI "\fBSortedTree\fP (T \fBnot_found\fP=\-1)"
.br
.RI "コンストラクタ "
.ti -1c
.RI "T \fBmin\fP ()"
.br
.RI "最小値を返す "
.ti -1c
.RI "T \fBmax\fP ()"
.br
.RI "最大値を返す "
.ti -1c
.RI "T \fBpop_min\fP ()"
.br
.RI "最小値を返し、削除する "
.ti -1c
.RI "T \fBpop_max\fP ()"
.br
.RI "最大値を返し、削除する "
.ti -1c
.RI "bool \fBcontains\fP (T x)"
.br
.RI "x が含まれているか否かを返す "
.ti -1c
.RI "bool \fBdiscard\fP (T x)"
.br
.RI "x を削除する "
.ti -1c
.RI "T \fBgt\fP (T x)"
.br
.RI "x より大きい最小の値を返す "
.ti -1c
.RI "T \fBge\fP (T x)"
.br
.RI "x 以上最小の値を返す "
.ti -1c
.RI "T \fBlt\fP (T x)"
.br
.RI "x 未満最大の値を返す "
.ti -1c
.RI "T \fBle\fP (T x)"
.br
.RI "x 以下の最大の値を返す "
.ti -1c
.RI "int \fBcount_lt\fP (T x)"
.br
.RI "x より小さい値の個数を返す "
.ti -1c
.RI "int \fBcount_le\fP (T x)"
.br
.RI "x 以下の値の個数を返す "
.ti -1c
.RI "int \fBcount_gt\fP (T x)"
.br
.RI "x より大きい値の個数を返す "
.ti -1c
.RI "int \fBcount_ge\fP (T x)"
.br
.RI "x 以上の値の個数を返す "
.ti -1c
.RI "T \fBkth_min\fP (int k)"
.br
.RI "k(0-indexed) 番目に小さい値の個数を返す "
.ti -1c
.RI "T \fBkth_max\fP (int k)"
.br
.RI "k(0-indexed) 番目に大きい値の個数を返す "
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "T \fBnot_found\fP =\-1"
.br
.in -1c
.SH "詳解"
.PP 

.SS "template<typename T>
.br
struct SortedTree< T >"
.PP
 \fBsorted_tree\&.hpp\fP の \fB6\fP 行目に定義があります。
.SH "構築子と解体子"
.PP 
.SS "template<typename T> \fBSortedTree\fP< T >\fB::SortedTree\fP ()\fR [default]\fP"

.SS "template<typename T> \fBSortedTree\fP< T >\fB::SortedTree\fP (T not_found = \fR\-1\fP)\fR [inline]\fP"

.PP
コンストラクタ 
.PP
\fB引数\fP
.RS 4
\fInot_found\fP 指定の値が見つからなかったときに返す値 
.RE
.PP

.PP
 \fBsorted_tree\&.hpp\fP の \fB13\fP 行目に定義があります。
.PP
参照先 \fBnot_found\fP\&.
.SH "関数詳解"
.PP 
.SS "template<typename T> T \fBSortedTree\fP< T >::min ()\fR [inline]\fP"

.PP
最小値を返す 
.PP
 \fBsorted_tree\&.hpp\fP の \fB16\fP 行目に定義があります。
.PP
参照先 \fBnot_found\fP\&.
.SS "template<typename T> T \fBSortedTree\fP< T >::max ()\fR [inline]\fP"

.PP
最大値を返す 
.PP
 \fBsorted_tree\&.hpp\fP の \fB22\fP 行目に定義があります。
.PP
参照先 \fBnot_found\fP\&.
.SS "template<typename T> T \fBSortedTree\fP< T >::pop_min ()\fR [inline]\fP"

.PP
最小値を返し、削除する 
.PP
 \fBsorted_tree\&.hpp\fP の \fB28\fP 行目に定義があります。
.PP
参照先 \fBmin()\fP, \fBnot_found\fP\&.
.SS "template<typename T> T \fBSortedTree\fP< T >::pop_max ()\fR [inline]\fP"

.PP
最大値を返し、削除する 
.PP
 \fBsorted_tree\&.hpp\fP の \fB35\fP 行目に定義があります。
.PP
参照先 \fBmax()\fP, \fBnot_found\fP\&.
.SS "template<typename T> bool \fBSortedTree\fP< T >::contains (T x)\fR [inline]\fP"

.PP
x が含まれているか否かを返す 
.PP
 \fBsorted_tree\&.hpp\fP の \fB42\fP 行目に定義があります。
.SS "template<typename T> bool \fBSortedTree\fP< T >::discard (T x)\fR [inline]\fP"

.PP
x を削除する 
.PP
 \fBsorted_tree\&.hpp\fP の \fB45\fP 行目に定義があります。
.SS "template<typename T> T \fBSortedTree\fP< T >::gt (T x)\fR [inline]\fP"

.PP
x より大きい最小の値を返す 
.PP
 \fBsorted_tree\&.hpp\fP の \fB53\fP 行目に定義があります。
.PP
参照先 \fBnot_found\fP\&.
.SS "template<typename T> T \fBSortedTree\fP< T >::ge (T x)\fR [inline]\fP"

.PP
x 以上最小の値を返す 
.PP
 \fBsorted_tree\&.hpp\fP の \fB60\fP 行目に定義があります。
.PP
参照先 \fBnot_found\fP\&.
.SS "template<typename T> T \fBSortedTree\fP< T >::lt (T x)\fR [inline]\fP"

.PP
x 未満最大の値を返す 
.PP
 \fBsorted_tree\&.hpp\fP の \fB67\fP 行目に定義があります。
.PP
参照先 \fBnot_found\fP\&.
.SS "template<typename T> T \fBSortedTree\fP< T >::le (T x)\fR [inline]\fP"

.PP
x 以下の最大の値を返す 
.PP
 \fBsorted_tree\&.hpp\fP の \fB74\fP 行目に定義があります。
.PP
参照先 \fBnot_found\fP\&.
.SS "template<typename T> int \fBSortedTree\fP< T >::count_lt (T x)\fR [inline]\fP"

.PP
x より小さい値の個数を返す 
.PP
 \fBsorted_tree\&.hpp\fP の \fB81\fP 行目に定義があります。
.SS "template<typename T> int \fBSortedTree\fP< T >::count_le (T x)\fR [inline]\fP"

.PP
x 以下の値の個数を返す 
.PP
 \fBsorted_tree\&.hpp\fP の \fB84\fP 行目に定義があります。
.SS "template<typename T> int \fBSortedTree\fP< T >::count_gt (T x)\fR [inline]\fP"

.PP
x より大きい値の個数を返す 
.PP
 \fBsorted_tree\&.hpp\fP の \fB87\fP 行目に定義があります。
.SS "template<typename T> int \fBSortedTree\fP< T >::count_ge (T x)\fR [inline]\fP"

.PP
x 以上の値の個数を返す 
.PP
 \fBsorted_tree\&.hpp\fP の \fB90\fP 行目に定義があります。
.SS "template<typename T> T \fBSortedTree\fP< T >::kth_min (int k)\fR [inline]\fP"

.PP
k(0-indexed) 番目に小さい値の個数を返す 
.PP
 \fBsorted_tree\&.hpp\fP の \fB93\fP 行目に定義があります。
.SS "template<typename T> T \fBSortedTree\fP< T >::kth_max (int k)\fR [inline]\fP"

.PP
k(0-indexed) 番目に大きい値の個数を返す 
.PP
 \fBsorted_tree\&.hpp\fP の \fB96\fP 行目に定義があります。
.SH "メンバ詳解"
.PP 
.SS "template<typename T> T \fBSortedTree\fP< T >::not_found =\-1"

.PP
 \fBsorted_tree\&.hpp\fP の \fB8\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
