.TH "SparseTableDisjoint< Semigroup >" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SparseTableDisjoint< Semigroup > \- スパーステーブル（Disjoint）  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'sparse_table_disjoint\&.hpp'\fP
.SS "公開型"

.in +1c
.ti -1c
.RI "using \fBType\fP = typename Semigroup::Type"
.br
.in -1c
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBSparseTableDisjoint\fP ()=default"
.br
.ti -1c
.RI "\fBSparseTableDisjoint\fP (const vector< \fBType\fP > &v)"
.br
.RI "配列 v からDisjoint Sparse Tableを構築する "
.ti -1c
.RI "\fBType\fP \fBfold\fP (int l, int r)"
.br
.RI "区間 [l, r) の半群積を返す "
.ti -1c
.RI "\fBType\fP \fBoperator[]\fP (int i) const"
.br
.RI "i 番目の要素を返す "
.ti -1c
.RI "int \fBsize\fP ()"
.br
.RI "配列のサイズを返す "
.in -1c
.SH "詳解"
.PP 

.SS "template<typename Semigroup>
.br
struct SparseTableDisjoint< Semigroup >"スパーステーブル（Disjoint） 


.PP
\fBテンプレート引数\fP
.RS 4
\fISemigroup\fP 半群（結合則が成り立つこと） 
.RE
.PP

.PP
 \fBsparse_table_disjoint\&.hpp\fP の \fB6\fP 行目に定義があります。
.SH "型定義メンバ詳解"
.PP 
.SS "template<typename Semigroup> using \fBSparseTableDisjoint\fP< Semigroup >::Type = typename Semigroup::Type"

.PP
 \fBsparse_table_disjoint\&.hpp\fP の \fB7\fP 行目に定義があります。
.SH "構築子と解体子"
.PP 
.SS "template<typename Semigroup> \fBSparseTableDisjoint\fP< Semigroup >\fB::SparseTableDisjoint\fP ()\fR [default]\fP"

.SS "template<typename Semigroup> \fBSparseTableDisjoint\fP< Semigroup >\fB::SparseTableDisjoint\fP (const vector< \fBType\fP > & v)\fR [inline]\fP"

.PP
配列 v からDisjoint Sparse Tableを構築する 
.PP
\fB覚え書き\fP
.RS 4
O(N log(N)) 
.RE
.PP

.PP
 \fBsparse_table_disjoint\&.hpp\fP の \fB12\fP 行目に定義があります。
.SH "関数詳解"
.PP 
.SS "template<typename Semigroup> \fBType\fP \fBSparseTableDisjoint\fP< Semigroup >::fold (int l, int r)\fR [inline]\fP"

.PP
区間 [l, r) の半群積を返す 
.PP
\fB覚え書き\fP
.RS 4
O(1) 
.RE
.PP

.PP
 \fBsparse_table_disjoint\&.hpp\fP の \fB31\fP 行目に定義があります。
.SS "template<typename Semigroup> \fBType\fP \fBSparseTableDisjoint\fP< Semigroup >::operator[] (int i) const\fR [inline]\fP"

.PP
i 番目の要素を返す 
.PP
 \fBsparse_table_disjoint\&.hpp\fP の \fB39\fP 行目に定義があります。
.PP
参照先 \fBfold()\fP\&.
.SS "template<typename Semigroup> int \fBSparseTableDisjoint\fP< Semigroup >::size ()\fR [inline]\fP"

.PP
配列のサイズを返す 
.PP
 \fBsparse_table_disjoint\&.hpp\fP の \fB42\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
