.TH "data_structure/sparse_table_2d.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_structure/sparse_table_2d.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "void \fBSparseTable2DInit\fP (const \fBVVL\fP &a, bool is_min=true)"
.br
.ti -1c
.RI "\fBll\fP \fBSparseTable2DQuery\fP (int l, int r, int u, int d)"
.br
.in -1c
.SS "変数"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBh\fP"
.br
.ti -1c
.RI "   int \fBw\fP"
.br
.ti -1c
.RI "   \fBll\fP \fBsign\fP"
.br
.ti -1c
.RI "   \fBll\fP \fBdat\fP [12][12][1010][1010]"
.br
.ti -1c
.RI "   \fBll\fP \fBlog_table\fP [5050]"
.br
.ti -1c
.RI "} \fBSparseTable2D\fP"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "void SparseTable2DInit (const \fBVVL\fP & a, bool is_min = \fRtrue\fP)"

.PP
 \fBsparse_table_2d\&.hpp\fP の \fB10\fP 行目に定義があります。
.PP
参照先 \fBdat\fP, \fBh\fP, \fBlog_table\fP, \fBsign\fP, \fBw\fP\&.
.SS "\fBll\fP SparseTable2DQuery (int l, int r, int u, int d)"

.PP
 \fBsparse_table_2d\&.hpp\fP の \fB33\fP 行目に定義があります。
.PP
参照先 \fBdat\fP, \fBlog_table\fP, \fBsign\fP\&.
.SH "変数詳解"
.PP 
.SS "int h"

.PP
 \fBsparse_table_2d\&.hpp\fP の \fB4\fP 行目に定義があります。
.SS "int w"

.PP
 \fBsparse_table_2d\&.hpp\fP の \fB4\fP 行目に定義があります。
.SS "\fBll\fP sign"

.PP
 \fBsparse_table_2d\&.hpp\fP の \fB5\fP 行目に定義があります。
.SS "\fBll\fP dat[12][12][1010][1010]"

.PP
 \fBsparse_table_2d\&.hpp\fP の \fB6\fP 行目に定義があります。
.SS "\fBll\fP log_table[5050]"

.PP
 \fBsparse_table_2d\&.hpp\fP の \fB7\fP 行目に定義があります。
.SS "struct  { \&.\&.\&. }  SparseTable2D"

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
