.TH "data_structure/sqrt_tree.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_structure/sqrt_tree.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBSqrtTree< Abel >\fP"
.br
.RI "更新 O(1) クエリ O(sqrt(N)) の改造版セグ木 "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
