.TH "string/suffix_array.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
string/suffix_array.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "template<int C = 256> \fBVI\fP \fBSuffixArray\fP (string s)"
.br
.RI "Suffix Array "
.in -1c
.SH "関数詳解"
.PP 
.SS "template<int C = 256> \fBVI\fP SuffixArray (string s)"

.PP
Suffix Array \fRsa[i] = j <-> s[j:] が辞書順 i 番目\fP

.PP
O(n log(n)) \fBhttps://wk1080id.hatenablog.com/entry/2018/12/25/005926\fP 
.PP
 \fBsuffix_array\&.hpp\fP の \fB9\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
