.TH "template.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
template.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <bits/stdc++\&.h>\fP
.br

.SS "マクロ定義"

.in +1c
.ti -1c
.RI "#define \fBALL\fP(x)"
.br
.ti -1c
.RI "#define \fBIO\fP   ios::sync_with_stdio(false),cin\&.tie(nullptr);"
.br
.ti -1c
.RI "#define \fBREP\fP(i,  n)"
.br
.ti -1c
.RI "#define \fBFOR\fP(i,  a,  b)"
.br
.ti -1c
.RI "#define \fBROF\fP(i,  a,  b)"
.br
.ti -1c
.RI "#define \fBdebug\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBprint_line\fP"
.br
.in -1c
.SS "型定義"

.in +1c
.ti -1c
.RI "template<typename T> using \fBrpriority_queue\fP = priority_queue<T,vector<T>,greater<T>>"
.br
.ti -1c
.RI "using \fBll\fP = long long"
.br
.ti -1c
.RI "using \fBld\fP = long double"
.br
.ti -1c
.RI "using \fBull\fP = unsigned long long"
.br
.ti -1c
.RI "using \fBlll\fP = __int128_t"
.br
.ti -1c
.RI "using \fBVST\fP = vector<string>"
.br
.ti -1c
.RI "using \fBVI\fP = vector<int>"
.br
.ti -1c
.RI "using \fBVVI\fP = vector<\fBVI\fP>"
.br
.ti -1c
.RI "using \fBVL\fP = vector<\fBll\fP>"
.br
.ti -1c
.RI "using \fBVVL\fP = vector<\fBVL\fP>"
.br
.ti -1c
.RI "using \fBPL\fP = pair<\fBll\fP,\fBll\fP>"
.br
.ti -1c
.RI "using \fBVP\fP = vector<\fBPL\fP>"
.br
.ti -1c
.RI "using \fBWG\fP = vector<vector<pair<int,\fBll\fP>>>"
.br
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "template<typename T> int \fBLB\fP (const vector< T > &v, T x)"
.br
.ti -1c
.RI "template<typename T> int \fBUQ\fP (T &v)"
.br
.ti -1c
.RI "template<typename T> bool \fBchmax\fP (T &a, T b)"
.br
.ti -1c
.RI "template<typename T> bool \fBchmin\fP (T &a, T b)"
.br
.in -1c
.SS "変数"

.in +1c
.ti -1c
.RI "const int \fBINF\fP =1e9+10"
.br
.ti -1c
.RI "const \fBll\fP \fBINFL\fP =4e18"
.br
.in -1c
.SH "マクロ定義詳解"
.PP 
.SS "#define ALL( x)"
\fB値:\fP
.nf
(x)\&.begin(),(x)\&.end()
.PP
.fi

.PP
 \fBtemplate\&.hpp\fP の \fB5\fP 行目に定義があります。
.SS "#define IO   ios::sync_with_stdio(false),cin\&.tie(nullptr);"

.PP
 \fBtemplate\&.hpp\fP の \fB6\fP 行目に定義があります。
.SS "#define REP( i,  n)"
\fB値:\fP
.nf
for(ll i=0; i<(ll)(n); i++)
.PP
.fi

.PP
 \fBtemplate\&.hpp\fP の \fB7\fP 行目に定義があります。
.SS "#define FOR( i,  a,  b)"
\fB値:\fP
.nf
for(ll i=(ll)(a); i<(b); i++)
.PP
.fi

.PP
 \fBtemplate\&.hpp\fP の \fB8\fP 行目に定義があります。
.SS "#define ROF( i,  a,  b)"
\fB値:\fP
.nf
for(ll i=(ll)(b)\-1; i>=(a); i\-\-)
.PP
.fi

.PP
 \fBtemplate\&.hpp\fP の \fB9\fP 行目に定義があります。
.SS "#define debug( \&.\&.\&.)"

.PP
 \fBtemplate\&.hpp\fP の \fB24\fP 行目に定義があります。
.SS "#define print_line"

.PP
 \fBtemplate\&.hpp\fP の \fB25\fP 行目に定義があります。
.SH "型定義詳解"
.PP 
.SS "template<typename T> using \fBrpriority_queue\fP = priority_queue<T,vector<T>,greater<T>>"

.PP
 \fBtemplate\&.hpp\fP の \fB15\fP 行目に定義があります。
.SS "using \fBll\fP = long long"

.PP
 \fBtemplate\&.hpp\fP の \fB16\fP 行目に定義があります。
.SS "using \fBld\fP = long double"

.PP
 \fBtemplate\&.hpp\fP の \fB16\fP 行目に定義があります。
.SS "using \fBull\fP = unsigned long long"

.PP
 \fBtemplate\&.hpp\fP の \fB17\fP 行目に定義があります。
.SS "using \fBlll\fP = __int128_t"

.PP
 \fBtemplate\&.hpp\fP の \fB17\fP 行目に定義があります。
.SS "using \fBVST\fP = vector<string>"

.PP
 \fBtemplate\&.hpp\fP の \fB17\fP 行目に定義があります。
.SS "using \fBVI\fP = vector<int>"

.PP
 \fBtemplate\&.hpp\fP の \fB18\fP 行目に定義があります。
.SS "using \fBVVI\fP = vector<\fBVI\fP>"

.PP
 \fBtemplate\&.hpp\fP の \fB18\fP 行目に定義があります。
.SS "using \fBVL\fP = vector<\fBll\fP>"

.PP
 \fBtemplate\&.hpp\fP の \fB18\fP 行目に定義があります。
.SS "using \fBVVL\fP = vector<\fBVL\fP>"

.PP
 \fBtemplate\&.hpp\fP の \fB18\fP 行目に定義があります。
.SS "using \fBPL\fP = pair<\fBll\fP,\fBll\fP>"

.PP
 \fBtemplate\&.hpp\fP の \fB19\fP 行目に定義があります。
.SS "using \fBVP\fP = vector<\fBPL\fP>"

.PP
 \fBtemplate\&.hpp\fP の \fB19\fP 行目に定義があります。
.SS "using \fBWG\fP = vector<vector<pair<int,\fBll\fP>>>"

.PP
 \fBtemplate\&.hpp\fP の \fB19\fP 行目に定義があります。
.SH "関数詳解"
.PP 
.SS "template<typename T> int LB (const vector< T > & v, T x)"

.PP
 \fBtemplate\&.hpp\fP の \fB11\fP 行目に定義があります。
.SS "template<typename T> int UQ (T & v)"

.PP
 \fBtemplate\&.hpp\fP の \fB12\fP 行目に定義があります。
.SS "template<typename T> bool chmax (T & a, T b)"

.PP
 \fBtemplate\&.hpp\fP の \fB13\fP 行目に定義があります。
.SS "template<typename T> bool chmin (T & a, T b)"

.PP
 \fBtemplate\&.hpp\fP の \fB14\fP 行目に定義があります。
.SH "変数詳解"
.PP 
.SS "const int INF =1e9+10"

.PP
 \fBtemplate\&.hpp\fP の \fB16\fP 行目に定義があります。
.SS "const \fBll\fP INFL =4e18"

.PP
 \fBtemplate\&.hpp\fP の \fB16\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
