.TH "graph/topological_sort.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph/topological_sort.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "\fBVI\fP \fBTopologicalSort\fP (const \fBVVI\fP &g)"
.br
.RI "グラフ g をトポロジカルソートする "
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBVI\fP TopologicalSort (const \fBVVI\fP & g)"

.PP
グラフ g をトポロジカルソートする 
.PP
\fB覚え書き\fP
.RS 4
グラフにサイクルがある場合は空の配列を返す 

.PP
O(V+E) 
.RE
.PP

.PP
 \fBtopological_sort\&.hpp\fP の \fB6\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
