.TH "math/totient.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math/totient.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "\fBll\fP \fBTotient\fP (\fBll\fP n)"
.br
.RI "オイラーのtotient関数 "
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBll\fP Totient (\fBll\fP n)"

.PP
オイラーのtotient関数 n 以下で n と互いに素な自然数の個数を返す。 
.PP
\fB覚え書き\fP
.RS 4
O(sqrt(N)) 
.RE
.PP

.PP
 \fBtotient\&.hpp\fP の \fB6\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
