.TH "Trie" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Trie
.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'trie\&.hpp'\fP
.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBNode\fP"
.br
.in -1c
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBTrie\fP (int len)"
.br
.ti -1c
.RI "void \fBinsert\fP (const string &s)"
.br
.ti -1c
.RI "int \fBcount\fP (const string &s)"
.br
.ti -1c
.RI "void \fBerase\fP (const string &s)"
.br
.in -1c
.SH "詳解"
.PP 
 \fBtrie\&.hpp\fP の \fB1\fP 行目に定義があります。
.SH "構築子と解体子"
.PP 
.SS "Trie::Trie (int len)\fR [inline]\fP"

.PP
 \fBtrie\&.hpp\fP の \fB8\fP 行目に定義があります。
.SH "関数詳解"
.PP 
.SS "void Trie::insert (const string & s)\fR [inline]\fP"

.PP
 \fBtrie\&.hpp\fP の \fB14\fP 行目に定義があります。
.SS "int Trie::count (const string & s)\fR [inline]\fP"

.PP
 \fBtrie\&.hpp\fP の \fB29\fP 行目に定義があります。
.SS "void Trie::erase (const string & s)\fR [inline]\fP"

.PP
 \fBtrie\&.hpp\fP の \fB39\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
