.TH "Trie::Node" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Trie::Node
.SH SYNOPSIS
.br
.PP
.PP
\fR#include 'trie\&.hpp'\fP
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBNode\fP ()"
.br
.in -1c
.SS "公開変数類"

.in +1c
.ti -1c
.RI "array< int, 26 > \fBto\fP"
.br
.ti -1c
.RI "int \fBcount_of_end\fP =0"
.br
.ti -1c
.RI "int \fBcount_of_node\fP =0"
.br
.in -1c
.SH "詳解"
.PP 
 \fBtrie\&.hpp\fP の \fB2\fP 行目に定義があります。
.SH "構築子と解体子"
.PP 
.SS "Trie::Node::Node ()\fR [inline]\fP"

.PP
 \fBtrie\&.hpp\fP の \fB5\fP 行目に定義があります。
.SH "メンバ詳解"
.PP 
.SS "array<int,26> Trie::Node::to"

.PP
 \fBtrie\&.hpp\fP の \fB3\fP 行目に定義があります。
.SS "int Trie::Node::count_of_end =0"

.PP
 \fBtrie\&.hpp\fP の \fB4\fP 行目に定義があります。
.SS "int Trie::Node::count_of_node =0"

.PP
 \fBtrie\&.hpp\fP の \fB4\fP 行目に定義があります。

.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
