.TH "graph/two_sat.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph/two_sat.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./kyopro_library/graph/scc\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBTwoSat\fP"
.br
.RI "2-SAT "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
