.TH "string/util.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
string/util.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "\fBVI\fP \fBStringToVi\fP (const string &s, bool lower=true)"
.br
.RI "文字列を数列に変換する "
.ti -1c
.RI "\fBVI\fP \fBReadString\fP (bool lower=true)"
.br
.RI "入力から文字列を受け取って数列に変換する "
.ti -1c
.RI "string \fBViToString\fP (const \fBVI\fP &a, bool lower=true)"
.br
.RI "数列を文字列に変換する "
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBVI\fP StringToVi (const string & s, bool lower = \fRtrue\fP)"

.PP
文字列を数列に変換する 
.PP
 \fButil\&.hpp\fP の \fB5\fP 行目に定義があります。
.SS "\fBVI\fP ReadString (bool lower = \fRtrue\fP)"

.PP
入力から文字列を受け取って数列に変換する 
.PP
 \fButil\&.hpp\fP の \fB11\fP 行目に定義があります。
.SS "string ViToString (const \fBVI\fP & a, bool lower = \fRtrue\fP)"

.PP
数列を文字列に変換する 
.PP
 \fButil\&.hpp\fP の \fB17\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
