.TH "data_structure/wavelet_matrix.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_structure/wavelet_matrix.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "クラス"

.in +1c
.ti -1c
.RI "struct \fBSuccinctBitVector\fP"
.br
.ti -1c
.RI "struct \fBWaveletMatrix\fP"
.br
.RI "Wavelet Matrix \fBhttps://github.com/MitI-7/WaveletMatrix/tree/master/WaveletMatrix\fP \fBhttps://miti-7.hatenablog.com/entry/2019/02/01/152131\fP "
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
