.TH "others/xor128.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
others/xor128.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "\fBull\fP \fBXor128\fP ()"
.br
.RI "疑似乱数生成 "
.ti -1c
.RI "\fBll\fP \fBXor128\fP (\fBll\fP n)"
.br
.ti -1c
.RI "\fBll\fP \fBXor128\fP (\fBll\fP l, \fBll\fP r)"
.br
.ti -1c
.RI "\fBld\fP \fBXor128Prob\fP ()"
.br
.in -1c
.SH "関数詳解"
.PP 
.SS "\fBull\fP Xor128 ()"

.PP
疑似乱数生成 
.PP
 \fBxor128\&.hpp\fP の \fB5\fP 行目に定義があります。
.SS "\fBll\fP Xor128 (\fBll\fP n)"

.PP
 \fBxor128\&.hpp\fP の \fB17\fP 行目に定義があります。
.PP
参照先 \fBXor128()\fP\&.
.SS "\fBll\fP Xor128 (\fBll\fP l, \fBll\fP r)"

.PP
 \fBxor128\&.hpp\fP の \fB18\fP 行目に定義があります。
.PP
参照先 \fBXor128()\fP\&.
.SS "\fBld\fP Xor128Prob ()"

.PP
 \fBxor128\&.hpp\fP の \fB19\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
