.TH "math/xor_convolution.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math/xor_convolution.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "template<typename T> void \fBFHT\fP (vector< T > &a, bool inv=false)"
.br
.RI "高速アダマール変換 "
.ti -1c
.RI "template<typename T> vector< T > \fBXorConvolution\fP (vector< T > a, vector< T > b)"
.br
.RI "XOR Convolution "
.in -1c
.SH "関数詳解"
.PP 
.SS "template<typename T> void FHT (vector< T > & a, bool inv = \fRfalse\fP)"

.PP
高速アダマール変換 
.PP
 \fBxor_convolution\&.hpp\fP の \fB5\fP 行目に定義があります。
.SS "template<typename T> vector< T > XorConvolution (vector< T > a, vector< T > b)"

.PP
XOR Convolution C[k] = Σ(i^j = k) A[i]B[j] なる C を返す 
.PP
\fB覚え書き\fP
.RS 4
O(n log(n)) 
.RE
.PP

.PP
 \fBxor_convolution\&.hpp\fP の \fB19\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
