.TH "string/z_algorithm.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
string/z_algorithm.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "template<typename T = string> \fBVI\fP \fBZAlgorithm\fP (const T &s)"
.br
.RI "Z Algorithm "
.in -1c
.SH "関数詳解"
.PP 
.SS "template<typename T = string> \fBVI\fP ZAlgorithm (const T & s)"

.PP
Z Algorithm \fRret[i] = [0, n) と [i, n) の最長共通接頭辞の長さ\fP 
.PP
 \fBz_algorithm\&.hpp\fP の \fB6\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
