.TH "ZetaMobius" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZetaMobius \- ゼータ変換・メビウス変換  

.SH SYNOPSIS
.br
.PP
.SS "関数"

.in +1c
.ti -1c
.RI "template<typename Monoid> vector< typename Monoid::Type > \fBSubsetZeta\fP (vector< typename Monoid::Type > v)"
.br
.RI "高速ゼータ変換（下位集合） "
.ti -1c
.RI "template<typename Monoid> vector< typename Monoid::Type > \fBSupersetZeta\fP (vector< typename Monoid::Type > v)"
.br
.RI "高速ゼータ変換（上位集合） "
.ti -1c
.RI "template<typename Abel> vector< typename Abel::Type > \fBSubsetMobius\fP (vector< typename Abel::Type > v)"
.br
.RI "高速メビウス変換（下位集合） "
.ti -1c
.RI "template<typename Abel> vector< typename Abel::Type > \fBSupersetMobius\fP (vector< typename Abel::Type > v)"
.br
.RI "高速メビウス変換（上位集合） "
.in -1c
.SH "詳解"
.PP 
ゼータ変換・メビウス変換 
.SH "関数詳解"
.PP 
.SS "template<typename Monoid> vector< typename Monoid::Type > ZetaMobius::SubsetZeta (vector< typename Monoid::Type > v)"

.PP
高速ゼータ変換（下位集合） v'[s] = Σ_{t⊆s} v[t] なる v' を返す 
.PP
\fB覚え書き\fP
.RS 4
|v| = 2^N として O(N 2^N) 
.RE
.PP

.PP
 \fBzeta_mobius\&.hpp\fP の \fB9\fP 行目に定義があります。
.SS "template<typename Monoid> vector< typename Monoid::Type > ZetaMobius::SupersetZeta (vector< typename Monoid::Type > v)"

.PP
高速ゼータ変換（上位集合） v'[s] = Σ_{t⊇s} v[t] なる v' を返す 
.PP
\fB覚え書き\fP
.RS 4
|v| = 2^N として O(N 2^N) 
.RE
.PP

.PP
 \fBzeta_mobius\&.hpp\fP の \fB19\fP 行目に定義があります。
.SS "template<typename Abel> vector< typename Abel::Type > ZetaMobius::SubsetMobius (vector< typename Abel::Type > v)"

.PP
高速メビウス変換（下位集合） v[s] = Σ_{t⊆s} v'[t] なる v' を返す 
.PP
\fB覚え書き\fP
.RS 4
逆変換が必要なので、v は可換群の元である必要がある 

.PP
|v| = 2^N として O(N 2^N) 
.RE
.PP

.PP
 \fBzeta_mobius\&.hpp\fP の \fB30\fP 行目に定義があります。
.SS "template<typename Abel> vector< typename Abel::Type > ZetaMobius::SupersetMobius (vector< typename Abel::Type > v)"

.PP
高速メビウス変換（上位集合） v[s] = Σ_{t⊇s} v'[t] なる v' を返す 
.PP
\fB覚え書き\fP
.RS 4
逆変換が必要なので、v は可換群の元である必要がある 

.PP
|v| = 2^N として O(N 2^N) 
.RE
.PP

.PP
 \fBzeta_mobius\&.hpp\fP の \fB41\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
