.TH "algorithm/zeta_mobius_div_mul.hpp" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
algorithm/zeta_mobius_div_mul.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./kyopro_library/template\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./kyopro_library/math/prime_enumerate\&.hpp'\fP
.br

.SS "名前空間"

.in +1c
.ti -1c
.RI "namespace \fBZetaMobiusDivMul\fP"
.br
.RI "倍数・約数ゼータ・メビウス変換 "
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "void \fBZetaMobiusDivMul::Init\fP (int n=1e6)"
.br
.ti -1c
.RI "template<typename Monoid> vector< typename Monoid::Type > \fBZetaMobiusDivMul::MultipleZeta\fP (vector< typename Monoid::Type > v)"
.br
.RI "倍数高速ゼータ変換 "
.ti -1c
.RI "template<typename Monoid> vector< typename Monoid::Type > \fBZetaMobiusDivMul::DivisorZeta\fP (vector< typename Monoid::Type > v)"
.br
.RI "約数高速ゼータ変換 "
.ti -1c
.RI "template<typename Abel> vector< typename Abel::Type > \fBZetaMobiusDivMul::MultipleMobius\fP (vector< typename Abel::Type > v)"
.br
.RI "倍数高速メビウス変換 "
.ti -1c
.RI "template<typename Abel> vector< typename Abel::Type > \fBZetaMobiusDivMul::DivisorMobius\fP (vector< typename Abel::Type > v)"
.br
.RI "約数高速メビウス変換 "
.in -1c
.SS "変数"

.in +1c
.ti -1c
.RI "\fBVI\fP \fBZetaMobiusDivMul::primes\fP"
.br
.in -1c
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
