.TH "ZetaMobiusDivMul" 3 "Kyopro Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZetaMobiusDivMul \- 倍数・約数ゼータ・メビウス変換  

.SH SYNOPSIS
.br
.PP
.SS "関数"

.in +1c
.ti -1c
.RI "void \fBInit\fP (int n=1e6)"
.br
.ti -1c
.RI "template<typename Monoid> vector< typename Monoid::Type > \fBMultipleZeta\fP (vector< typename Monoid::Type > v)"
.br
.RI "倍数高速ゼータ変換 "
.ti -1c
.RI "template<typename Monoid> vector< typename Monoid::Type > \fBDivisorZeta\fP (vector< typename Monoid::Type > v)"
.br
.RI "約数高速ゼータ変換 "
.ti -1c
.RI "template<typename Abel> vector< typename Abel::Type > \fBMultipleMobius\fP (vector< typename Abel::Type > v)"
.br
.RI "倍数高速メビウス変換 "
.ti -1c
.RI "template<typename Abel> vector< typename Abel::Type > \fBDivisorMobius\fP (vector< typename Abel::Type > v)"
.br
.RI "約数高速メビウス変換 "
.in -1c
.SS "変数"

.in +1c
.ti -1c
.RI "\fBVI\fP \fBprimes\fP"
.br
.in -1c
.SH "詳解"
.PP 
倍数・約数ゼータ・メビウス変換 
.SH "関数詳解"
.PP 
.SS "void ZetaMobiusDivMul::Init (int n = \fR1e6\fP)"

.PP
 \fBzeta_mobius_div_mul\&.hpp\fP の \fB7\fP 行目に定義があります。
.SS "template<typename Monoid> vector< typename Monoid::Type > ZetaMobiusDivMul::MultipleZeta (vector< typename Monoid::Type > v)"

.PP
倍数高速ゼータ変換 v'[k] = Σ_{k|d} v[d] なる v' を返す 
.PP
\fB覚え書き\fP
.RS 4
O(N log(log(N))) 
.RE
.PP

.PP
 \fBzeta_mobius_div_mul\&.hpp\fP の \fB13\fP 行目に定義があります。
.PP
参照先 \fBInit()\fP\&.
.SS "template<typename Monoid> vector< typename Monoid::Type > ZetaMobiusDivMul::DivisorZeta (vector< typename Monoid::Type > v)"

.PP
約数高速ゼータ変換 v'[k] = Σ_{d|k} v[d] なる v' を返す 
.PP
\fB覚え書き\fP
.RS 4
O(N log(log(N))) 
.RE
.PP

.PP
 \fBzeta_mobius_div_mul\&.hpp\fP の \fB24\fP 行目に定義があります。
.PP
参照先 \fBInit()\fP\&.
.SS "template<typename Abel> vector< typename Abel::Type > ZetaMobiusDivMul::MultipleMobius (vector< typename Abel::Type > v)"

.PP
倍数高速メビウス変換 v'[k] = Σ_{k|d} μ(d) v[d] なる v' を返す 
.PP
\fB覚え書き\fP
.RS 4
逆変換が必要なので、v は可換群の元である必要がある 

.PP
O(N log(log(N))) 
.RE
.PP

.PP
 \fBzeta_mobius_div_mul\&.hpp\fP の \fB36\fP 行目に定義があります。
.PP
参照先 \fBInit()\fP\&.
.SS "template<typename Abel> vector< typename Abel::Type > ZetaMobiusDivMul::DivisorMobius (vector< typename Abel::Type > v)"

.PP
約数高速メビウス変換 v'[k] = Σ_{d|k} μ(d) v[k/d] なる v' を返す 
.PP
\fB覚え書き\fP
.RS 4
逆変換が必要なので、v は可換群の元である必要がある 

.PP
O(N log(log(N))) 
.RE
.PP

.PP
 \fBzeta_mobius_div_mul\&.hpp\fP の \fB48\fP 行目に定義があります。
.PP
参照先 \fBInit()\fP\&.
.SH "変数詳解"
.PP 
.SS "\fBVI\fP ZetaMobiusDivMul::primes"

.PP
 \fBzeta_mobius_div_mul\&.hpp\fP の \fB6\fP 行目に定義があります。
.SH "著者"
.PP 
 Kyopro Libraryのソースコードから抽出しました。
