#!/bin/bash

# 環境側でやること
# 1. GCCのインストール
#   - C++20が使える
#   - #include <bits/stdc++.h> が使える
# 2. Python3のインストール
# 3. ~/.vimrc を設定する

# chmod +x build

git clone https://github.com/Today017/kyopro_library.git
cd kyopro_library
git checkout env
cd ..

cp -r ./folder/hoge/* .

chmod +x test
chmod +x cmp
chmod +x copy
chmod +x contest
chmod +x test

mkdir random_test
touch random_test/generate.cpp
touch random_test/naive.cpp

mkdir esc

git clone https://github.com/Today017/ac-library.git
cp -r ac-library/atcoder .
mv ac-library atcoder/