var annotated_dup =
[
    [ "Abel", "namespace_abel.html", [
      [ "Sum", "struct_abel_1_1_sum.html", "struct_abel_1_1_sum" ],
      [ "Xor", "struct_abel_1_1_xor.html", "struct_abel_1_1_xor" ]
    ] ],
    [ "exp", "namespaceexp.html", [
      [ "Expander", "classexp_1_1_expander.html", "classexp_1_1_expander" ]
    ] ],
    [ "Geometry", "namespace_geometry.html", [
      [ "Circle", "struct_geometry_1_1_circle.html", "struct_geometry_1_1_circle" ],
      [ "Line", "struct_geometry_1_1_line.html", "struct_geometry_1_1_line" ],
      [ "Point", "struct_geometry_1_1_point.html", "struct_geometry_1_1_point" ],
      [ "Segment", "struct_geometry_1_1_segment.html", "struct_geometry_1_1_segment" ]
    ] ],
    [ "InsertableReversibleArrayImpl", "namespace_insertable_reversible_array_impl.html", [
      [ "LazyReversibleRBST", "struct_insertable_reversible_array_impl_1_1_lazy_reversible_r_b_s_t.html", "struct_insertable_reversible_array_impl_1_1_lazy_reversible_r_b_s_t" ],
      [ "LazyReversibleRBSTNode", "struct_insertable_reversible_array_impl_1_1_lazy_reversible_r_b_s_t_node.html", "struct_insertable_reversible_array_impl_1_1_lazy_reversible_r_b_s_t_node" ],
      [ "RBSTBase", "struct_insertable_reversible_array_impl_1_1_r_b_s_t_base.html", "struct_insertable_reversible_array_impl_1_1_r_b_s_t_base" ]
    ] ],
    [ "Monoid", "namespace_monoid.html", [
      [ "Max", "struct_monoid_1_1_max.html", "struct_monoid_1_1_max" ],
      [ "Min", "struct_monoid_1_1_min.html", "struct_monoid_1_1_min" ],
      [ "Sum", "struct_monoid_1_1_sum.html", "struct_monoid_1_1_sum" ],
      [ "SumPair", "struct_monoid_1_1_sum_pair.html", "struct_monoid_1_1_sum_pair" ]
    ] ],
    [ "Operator", "namespace_operator.html", [
      [ "Add", "struct_operator_1_1_add.html", "struct_operator_1_1_add" ],
      [ "Update", "struct_operator_1_1_update.html", "struct_operator_1_1_update" ],
      [ "UpdateTimeStamp", "struct_operator_1_1_update_time_stamp.html", "struct_operator_1_1_update_time_stamp" ]
    ] ],
    [ "RangeQuery", "namespace_range_query.html", [
      [ "ApplyAdd", "struct_range_query_1_1_apply_add.html", "struct_range_query_1_1_apply_add" ],
      [ "ApplyAdd_GetMax", "struct_range_query_1_1_apply_add___get_max.html", "struct_range_query_1_1_apply_add___get_max" ],
      [ "ApplyAdd_GetMin", "struct_range_query_1_1_apply_add___get_min.html", "struct_range_query_1_1_apply_add___get_min" ],
      [ "ApplyAdd_GetSum", "struct_range_query_1_1_apply_add___get_sum.html", "struct_range_query_1_1_apply_add___get_sum" ],
      [ "ApplyUpdate", "struct_range_query_1_1_apply_update.html", "struct_range_query_1_1_apply_update" ],
      [ "ApplyUpdate_GetMax", "struct_range_query_1_1_apply_update___get_max.html", "struct_range_query_1_1_apply_update___get_max" ],
      [ "ApplyUpdate_GetMin", "struct_range_query_1_1_apply_update___get_min.html", "struct_range_query_1_1_apply_update___get_min" ],
      [ "ApplyUpdate_GetSum", "struct_range_query_1_1_apply_update___get_sum.html", "struct_range_query_1_1_apply_update___get_sum" ],
      [ "Max", "struct_range_query_1_1_max.html", "struct_range_query_1_1_max" ],
      [ "MaxDynamic", "struct_range_query_1_1_max_dynamic.html", "struct_range_query_1_1_max_dynamic" ],
      [ "Min", "struct_range_query_1_1_min.html", "struct_range_query_1_1_min" ],
      [ "MinDynamic", "struct_range_query_1_1_min_dynamic.html", "struct_range_query_1_1_min_dynamic" ],
      [ "Sum", "struct_range_query_1_1_sum.html", "struct_range_query_1_1_sum" ],
      [ "SumDynamic", "struct_range_query_1_1_sum_dynamic.html", "struct_range_query_1_1_sum_dynamic" ]
    ] ],
    [ "AngelBeats", "struct_angel_beats.html", "struct_angel_beats" ],
    [ "ArithmeticProgression", "struct_arithmetic_progression.html", "struct_arithmetic_progression" ],
    [ "BezoutIdentity", "struct_bezout_identity.html", "struct_bezout_identity" ],
    [ "BiInfo", "struct_bi_info.html", "struct_bi_info" ],
    [ "BinaryTrie", "struct_binary_trie.html", "struct_binary_trie" ],
    [ "BridgeInfo", "struct_bridge_info.html", "struct_bridge_info" ],
    [ "BurningBurying", "struct_burning_burying.html", "struct_burning_burying" ],
    [ "CHT", "struct_c_h_t.html", "struct_c_h_t" ],
    [ "CombinationLucas", "struct_combination_lucas.html", "struct_combination_lucas" ],
    [ "Combinatorics", "struct_combinatorics.html", "struct_combinatorics" ],
    [ "CumulativeSum2D", "struct_cumulative_sum2_d.html", "struct_cumulative_sum2_d" ],
    [ "Doubling", "struct_doubling.html", "struct_doubling" ],
    [ "DoublingFold", "struct_doubling_fold.html", "struct_doubling_fold" ],
    [ "DSU", "struct_d_s_u.html", "struct_d_s_u" ],
    [ "DsuBaseSemigroup", "struct_dsu_base_semigroup.html", "struct_dsu_base_semigroup" ],
    [ "DsuMerging", "struct_dsu_merging.html", "struct_dsu_merging" ],
    [ "DsuPotentialized", "struct_dsu_potentialized.html", "struct_dsu_potentialized" ],
    [ "DsuRollback", "struct_dsu_rollback.html", "struct_dsu_rollback" ],
    [ "DynamicConnectivity", "struct_dynamic_connectivity.html", "struct_dynamic_connectivity" ],
    [ "DynamicModInt", "struct_dynamic_mod_int.html", "struct_dynamic_mod_int" ],
    [ "ErasablePQ", "struct_erasable_p_q.html", "struct_erasable_p_q" ],
    [ "Factors", "struct_factors.html", "struct_factors" ],
    [ "FenwickTree", "struct_fenwick_tree.html", "struct_fenwick_tree" ],
    [ "Fraction", "struct_fraction.html", "struct_fraction" ],
    [ "Hash", "struct_hash.html", "struct_hash" ],
    [ "HLD", "struct_h_l_d.html", "struct_h_l_d" ],
    [ "InsertableReversibleArray", "struct_insertable_reversible_array.html", "struct_insertable_reversible_array" ],
    [ "LCA", "struct_l_c_a.html", "struct_l_c_a" ],
    [ "LcaEdge", "struct_lca_edge.html", "struct_lca_edge" ],
    [ "LcaVertex", "struct_lca_vertex.html", "struct_lca_vertex" ],
    [ "MaxFlow", "struct_max_flow.html", "struct_max_flow" ],
    [ "MergeSortTree", "struct_merge_sort_tree.html", "struct_merge_sort_tree" ],
    [ "MinCostFlow", "struct_min_cost_flow.html", "struct_min_cost_flow" ],
    [ "Mo", "struct_mo.html", "struct_mo" ],
    [ "ModInt", "struct_mod_int.html", "struct_mod_int" ],
    [ "MultiSet", "struct_multi_set.html", "struct_multi_set" ],
    [ "NTT", "class_n_t_t.html", "class_n_t_t" ],
    [ "OffsetVector", "struct_offset_vector.html", "struct_offset_vector" ],
    [ "RangeSet", "struct_range_set.html", "struct_range_set" ],
    [ "RollingHash", "struct_rolling_hash.html", "struct_rolling_hash" ],
    [ "SccInfo", "struct_scc_info.html", "struct_scc_info" ],
    [ "SegmentTree2D", "struct_segment_tree2_d.html", "struct_segment_tree2_d" ],
    [ "SegTree", "struct_seg_tree.html", "struct_seg_tree" ],
    [ "SegTreeDual", "struct_seg_tree_dual.html", "struct_seg_tree_dual" ],
    [ "SegTreeDynamic", "struct_seg_tree_dynamic.html", "struct_seg_tree_dynamic" ],
    [ "SegTreeLazy", "struct_seg_tree_lazy.html", "struct_seg_tree_lazy" ],
    [ "Set", "struct_set.html", "struct_set" ],
    [ "SortedMultiTree", "struct_sorted_multi_tree.html", "struct_sorted_multi_tree" ],
    [ "SortedTree", "struct_sorted_tree.html", "struct_sorted_tree" ],
    [ "SparseTable", "struct_sparse_table.html", "struct_sparse_table" ],
    [ "SparseTableDisjoint", "struct_sparse_table_disjoint.html", "struct_sparse_table_disjoint" ],
    [ "SqrtTree", "struct_sqrt_tree.html", "struct_sqrt_tree" ],
    [ "SuccinctBitVector", "struct_succinct_bit_vector.html", "struct_succinct_bit_vector" ],
    [ "Timer", "struct_timer.html", "struct_timer" ],
    [ "Trie", "struct_trie.html", "struct_trie" ],
    [ "TwoSat", "struct_two_sat.html", "struct_two_sat" ],
    [ "WaveletMatrix", "struct_wavelet_matrix.html", "struct_wavelet_matrix" ]
];