Kyopro Library: exp.Expander Class Reference
exp.Expander Class Reference
Expander class is responsible for expanding libraries in the source code.
Public Member Functions
bool is_ignored_line (self, line)
Checks if a line should be ignored during expansion.
__init__ (self, List[Path] lib_paths)
Initializes an Expander object.
Path find_library (self, str library_name)
Finds the path of a library file.
List[str] expand_library (self, Path library_file_path)
Expands a library file.
str expand (self, str source)
Expands libraries in the source code.
Public Attributes
lib_paths = lib_paths
Static Public Attributes
include = re.compile(r'#include\s*["<](kyopro_library/[a-z0-9_/]*(|.hpp))[">]\s*')
included = set()
Detailed Description
Expander class is responsible for expanding libraries in the source code.
Attributes:
include (re.Pattern): Regular expression pattern to match include statements.
lib_paths (List[Path]): List of library paths.
included (Set[Path]): Set of included library file paths.
Methods:
is_ignored_line(line: str) -> bool: Checks if a line should be ignored during expansion.
find_library(library_name: str) -> Path: Finds the path of a library file.
expand_library(library_file_path: Path) -> List[str]: Expands a library file.
expand(source: str) -> str: Expands libraries in the source code.
Definition at line 21 of file exp.py.
Constructor & Destructor Documentation
__init__()
exp.Expander.__init__ (self, List[Path] lib_paths)
Initializes an Expander object.
Args:
lib_paths (List[Path]): List of library paths.
Definition at line 67 of file exp.py.
Member Function Documentation
expand()
str exp.Expander.expand (self, str source)
Expands libraries in the source code.
Args:
source (str): The source code to be expanded.
Returns:
str: The expanded source code.
Definition at line 145 of file exp.py.
References expand_library(), find_library(), include, and included.
expand_library()
List[str] exp.Expander.expand_library (self, Path library_file_path)
Expands a library file.
Args:
library_file_path (Path): The path of the library file.
Returns:
List[str]: The expanded lines of the library file.
Definition at line 100 of file exp.py.
References expand_library(), find_library(), exp.format, include, included, and is_ignored_line().
find_library()
Path exp.Expander.find_library (self, str library_name)
Finds the path of a library file.
Args:
library_name (str): The name of the library file.
Returns:
Path: The path of the library file.
Raises:
FileNotFoundError: If the library file cannot be found.
Definition at line 79 of file exp.py.
References exp.format, and lib_paths.
is_ignored_line()
bool exp.Expander.is_ignored_line (self, line)
Checks if a line should be ignored during expansion.
Args:
line (str): The line to be checked.
Returns:
bool: True if the line should be ignored, False otherwise.
Definition at line 40 of file exp.py.
Member Data Documentation
include
exp.Expander.include = re.compile(r'#include\s*["<](kyopro_library/[a-z0-9_/]*(|.hpp))[">]\s*') static
Definition at line 38 of file exp.py.
included
exp.Expander.included = set() static
Definition at line 77 of file exp.py.
lib_paths
exp.Expander.lib_paths = lib_paths
Definition at line 75 of file exp.py.
The documentation for this class was generated from the following file:
kyopro_tools/exp.py