Kyopro Library: mod_reconstruct Namespace Reference
mod_reconstruct Namespace Reference
Functions
reconstruct (n, mod)
add_rational_expression (original, mod)
main ()
Function Documentation
add_rational_expression()
mod_reconstruct.add_rational_expression (original, mod)
Definition at line 19 of file mod_reconstruct.py.
References reconstruct().
main()
mod_reconstruct.main ()
Definition at line 50 of file mod_reconstruct.py.
References add_rational_expression(), and main().
reconstruct()
mod_reconstruct.reconstruct (n, mod)
Definition at line 3 of file mod_reconstruct.py.