Kyopro Library: Hash Struct Reference
Hash Struct Reference
#include <rolling_hash.hpp>
Public Types
using Type = array<ll,5>
Public Member Functions
void init ()
Hash ()=default
Hash (const Hash &other)
Hash (char c)
Hash & operator+= (const Hash &other)
Hash & operator-= (const Hash &other)
Hash operator+ (const Hash &other) const
Hash operator- (const Hash &other) const
Hash shift (int x) const
bool operator== (const Hash &other) const
Hash & operator= (const Hash &other)
Public Attributes
Type value
Static Public Attributes
static VL base
static VVL inv
static VVL pow
static const VL mod ={1000000007,1000000009,1000000021,1000000033,1000000087}
static bool flag =false
static array< array< ll, 5 >, 256 > num ={}
Detailed Description
Definition at line 7 of file rolling_hash.hpp.
Member Typedef Documentation
Type
using Hash::Type = array<ll,5>
Definition at line 9 of file rolling_hash.hpp.
Constructor & Destructor Documentation
Hash() [1/3]
Hash::Hash () default
Hash() [2/3]
Hash::Hash (const Hash & other) inline
Definition at line 35 of file rolling_hash.hpp.
References flag, and init().
Hash() [3/3]
Hash::Hash (char c) inline
Definition at line 39 of file rolling_hash.hpp.
References flag, and init().
Member Function Documentation
init()
void Hash::init () inline
Definition at line 18 of file rolling_hash.hpp.
References flag, HASH_C, HASH_MAX, and Xor128().
operator+()
Hash Hash::operator+ (const Hash & other) const inline
Definition at line 53 of file rolling_hash.hpp.
References operator+=().
operator+=()
Hash & Hash::operator+= (const Hash & other) inline
Definition at line 45 of file rolling_hash.hpp.
operator-()
Hash Hash::operator- (const Hash & other) const inline
Definition at line 58 of file rolling_hash.hpp.
References operator-=().
operator-=()
Hash & Hash::operator-= (const Hash & other) inline
Definition at line 49 of file rolling_hash.hpp.
operator=()
Hash & Hash::operator= (const Hash & other) inline
Definition at line 73 of file rolling_hash.hpp.
operator==()
bool Hash::operator== (const Hash & other) const inline
Definition at line 69 of file rolling_hash.hpp.
shift()
Hash Hash::shift (int x) const inline
Definition at line 63 of file rolling_hash.hpp.
Member Data Documentation
base
VL Hash::base static
Definition at line 10 of file rolling_hash.hpp.
flag
bool Hash::flag =false static
Definition at line 13 of file rolling_hash.hpp.
inv
VVL Hash::inv static
Definition at line 11 of file rolling_hash.hpp.
mod
const VL Hash::mod ={1000000007,1000000009,1000000021,1000000033,1000000087} static
Definition at line 82 of file rolling_hash.hpp.
num
array< array< ll, 5 >, HASH_C > Hash::num ={} static
Definition at line 84 of file rolling_hash.hpp.
pow
VVL Hash::pow static
Definition at line 11 of file rolling_hash.hpp.
value
Type Hash::value
Definition at line 16 of file rolling_hash.hpp.
The documentation for this struct was generated from the following file:
string/rolling_hash.hpp