Kyopro Library: InsertableReversibleArrayImpl::LazyReversibleRBST< T, E, f, g, h, ts > Struct Template Reference
InsertableReversibleArrayImpl::LazyReversibleRBST< T, E, f, g, h, ts > Struct Template Reference
#include <insert_reverse_array.hpp>
Public Types
using Node = LazyReversibleRBSTNode<T,E>
using base = RBSTBase<LazyReversibleRBSTNode<T,E>>
Public Types inherited from InsertableReversibleArrayImpl::RBSTBase< LazyReversibleRBSTNode< T, E > >
using Ptr
Public Member Functions
LazyReversibleRBST ()=default
void toggle (Ptr t)
T fold (Ptr &t, int a, int b)
void reverse (Ptr &t, int a, int b)
void apply (Ptr &t, int a, int b, const E &e)
Ptr merge (Ptr l, Ptr r)
pair< Ptr, Ptr > split (Ptr t, int k)
Public Member Functions inherited from InsertableReversibleArrayImpl::RBSTBase< LazyReversibleRBSTNode< T, E > >
Ptr my_new (Args...args)
void my_del (Ptr t)
Ptr make_tree () const
int size (Ptr t) const
Ptr merge (Ptr l, Ptr r)
pair< Ptr, Ptr > split (Ptr t, int k)
Ptr build (int l, int r, const vector< decltype(LazyReversibleRBSTNode< T, E >::key)> &v)
Ptr build (const vector< decltype(LazyReversibleRBSTNode< T, E >::key)> &v)
void insert (Ptr &t, int k, const Args &...args)
void erase (Ptr &t, int k)
Ptr my_new (Args...args)
void my_del (Ptr t)
Ptr make_tree () const
int size (Ptr t) const
Ptr merge (Ptr l, Ptr r)
pair< Ptr, Ptr > split (Ptr t, int k)
Ptr build (int l, int r, const vector< decltype(LazyReversibleRBSTNode< T, E >::key)> &v)
Ptr build (const vector< decltype(LazyReversibleRBSTNode< T, E >::key)> &v)
void insert (Ptr &t, int k, const Args &...args)
void erase (Ptr &t, int k)
Protected Member Functions
T sum (const Ptr t) const
Ptr update (Ptr t) override
void push (Ptr t) override
void propagate (Ptr t, const E &x)
Protected Member Functions inherited from InsertableReversibleArrayImpl::RBSTBase< LazyReversibleRBSTNode< T, E > >
int count (const Ptr t) const
int count (const Ptr t) const
Additional Inherited Members
Static Protected Member Functions inherited from InsertableReversibleArrayImpl::RBSTBase< LazyReversibleRBSTNode< T, E > >
static uint64_t rng ()
static uint64_t rng ()
Detailed Description
template<typename T, typename E, T(*)(T, T) f, T(*)(T, E) g, E(*)(E, E) h, T(*)(T) ts>
struct InsertableReversibleArrayImpl::LazyReversibleRBST< T, E, f, g, h, ts >
Definition at line 81 of file insert_reverse_array.hpp.
Member Typedef Documentation
base
template<typename T, typename E, T(*)(T, T) f, T(*)(T, E) g, E(*)(E, E) h, T(*)(T) ts> using InsertableReversibleArrayImpl::LazyReversibleRBST< T, E, f, g, h, ts >::base = RBSTBase<LazyReversibleRBSTNode<T,E>>
Definition at line 83 of file insert_reverse_array.hpp.
Node
template<typename T, typename E, T(*)(T, T) f, T(*)(T, E) g, E(*)(E, E) h, T(*)(T) ts> using InsertableReversibleArrayImpl::LazyReversibleRBST< T, E, f, g, h, ts >::Node = LazyReversibleRBSTNode<T,E>
Definition at line 82 of file insert_reverse_array.hpp.
Constructor & Destructor Documentation
LazyReversibleRBST()
template<typename T, typename E, T(*)(T, T) f, T(*)(T, E) g, E(*)(E, E) h, T(*)(T) ts> InsertableReversibleArrayImpl::LazyReversibleRBST< T, E, f, g, h, ts >::LazyReversibleRBST () default
Member Function Documentation
apply()
template<typename T, typename E, T(*)(T, T) f, T(*)(T, E) g, E(*)(E, E) h, T(*)(T) ts> void InsertableReversibleArrayImpl::LazyReversibleRBST< T, E, f, g, h, ts >::apply (Ptr & t, int a, int b, const E & e) inline
Definition at line 107 of file insert_reverse_array.hpp.
References propagate().
fold()
template<typename T, typename E, T(*)(T, T) f, T(*)(T, E) g, E(*)(E, E) h, T(*)(T) ts> T InsertableReversibleArrayImpl::LazyReversibleRBST< T, E, f, g, h, ts >::fold (Ptr & t, int a, int b) inline
Definition at line 94 of file insert_reverse_array.hpp.
References sum().
merge()
template<typename T, typename E, T(*)(T, T) f, T(*)(T, E) g, E(*)(E, E) h, T(*)(T) ts> Ptr InsertableReversibleArrayImpl::RBSTBase< LazyReversibleRBSTNode< T, E > >::merge (Ptr l, Ptr r) inline
Definition at line 12 of file insert_reverse_array.hpp.
propagate()
template<typename T, typename E, T(*)(T, T) f, T(*)(T, E) g, E(*)(E, E) h, T(*)(T) ts> void InsertableReversibleArrayImpl::LazyReversibleRBST< T, E, f, g, h, ts >::propagate (Ptr t, const E & x) inline protected
Definition at line 136 of file insert_reverse_array.hpp.
push()
template<typename T, typename E, T(*)(T, T) f, T(*)(T, E) g, E(*)(E, E) h, T(*)(T) ts> void InsertableReversibleArrayImpl::LazyReversibleRBST< T, E, f, g, h, ts >::push (Ptr t) inline override protected virtual
Implements InsertableReversibleArrayImpl::RBSTBase< LazyReversibleRBSTNode< T, E > >.
Definition at line 124 of file insert_reverse_array.hpp.
References propagate(), and toggle().
reverse()
template<typename T, typename E, T(*)(T, T) f, T(*)(T, E) g, E(*)(E, E) h, T(*)(T) ts> void InsertableReversibleArrayImpl::LazyReversibleRBST< T, E, f, g, h, ts >::reverse (Ptr & t, int a, int b) inline
Definition at line 101 of file insert_reverse_array.hpp.
References toggle().
split()
template<typename T, typename E, T(*)(T, T) f, T(*)(T, E) g, E(*)(E, E) h, T(*)(T) ts> pair< Ptr, Ptr > InsertableReversibleArrayImpl::RBSTBase< LazyReversibleRBSTNode< T, E > >::split (Ptr t, int k) inline
Definition at line 24 of file insert_reverse_array.hpp.
sum()
template<typename T, typename E, T(*)(T, T) f, T(*)(T, E) g, E(*)(E, E) h, T(*)(T) ts> T InsertableReversibleArrayImpl::LazyReversibleRBST< T, E, f, g, h, ts >::sum (const Ptr t) const inline protected
Definition at line 115 of file insert_reverse_array.hpp.
toggle()
template<typename T, typename E, T(*)(T, T) f, T(*)(T, E) g, E(*)(E, E) h, T(*)(T) ts> void InsertableReversibleArrayImpl::LazyReversibleRBST< T, E, f, g, h, ts >::toggle (Ptr t) inline
Definition at line 88 of file insert_reverse_array.hpp.
update()
template<typename T, typename E, T(*)(T, T) f, T(*)(T, E) g, E(*)(E, E) h, T(*)(T) ts> Ptr InsertableReversibleArrayImpl::LazyReversibleRBST< T, E, f, g, h, ts >::update (Ptr t) inline override protected virtual
Implements InsertableReversibleArrayImpl::RBSTBase< LazyReversibleRBSTNode< T, E > >.
Definition at line 116 of file insert_reverse_array.hpp.
References push().
The documentation for this struct was generated from the following file:
data_structure/insert_reverse_array.hpp