Kyopro Library: Geometry::Line Struct Reference
Geometry::Line Struct Reference
#include <geo.hpp>
Public Member Functions
Line ()=default
Line (const Point &_a, const Point &_b)
Line (const Real &A, const Real &B, const Real &C)
bool operator== (const Line &l) const
Public Attributes
Point a
Point b
Friends
istream & operator>> (istream &is, Line &l)
Detailed Description
Definition at line 31 of file geo.hpp.
Constructor & Destructor Documentation
Line() [1/3]
Geometry::Line::Line () default
Line() [2/3]
Geometry::Line::Line (const Point & _a, const Point & _b) inline
Definition at line 34 of file geo.hpp.
References a, and b.
Line() [3/3]
Geometry::Line::Line (const Real & A, const Real & B, const Real & C) inline
Definition at line 36 of file geo.hpp.
References a, Geometry::almostEqual(), b, and Geometry::Point::Point().
Member Function Documentation
operator==()
bool Geometry::Line::operator== (const Line & l) const inline
Definition at line 52 of file geo.hpp.
References a, b, and Geometry::Point::operator==().
Friends And Related Symbol Documentation
operator>>
istream & operator>> (istream & is, Line & l) friend
Definition at line 53 of file geo.hpp.
References a, and b.
Member Data Documentation
a
Point Geometry::Line::a
Definition at line 32 of file geo.hpp.
b
Point Geometry::Line::b
Definition at line 32 of file geo.hpp.
The documentation for this struct was generated from the following file:
geometry/geo.hpp