Kyopro Library: Geometry::Point Struct Reference
Geometry::Point Struct Reference
#include <geo.hpp>
Public Member Functions
Point ()=default
Point (Real x, Real y)
Point operator+ (const Point &p) const
Point operator- (const Point &p) const
Point operator* (Real k) const
Point operator/ (Real k) const
Real dot (const Point &p) const
Real cross (const Point &p) const
Real cross (const Point &p1, const Point &p2) const
Real norm () const
Real abs () const
Real arg () const
bool operator== (const Point &p) const
Public Attributes
Real x
Real y
Friends
istream & operator>> (istream &is, Point &p)
Detailed Description
Definition at line 13 of file geo.hpp.
Constructor & Destructor Documentation
Point() [1/2]
Geometry::Point::Point () default
Point() [2/2]
Geometry::Point::Point (Real x, Real y) inline
Definition at line 16 of file geo.hpp.
References x, and y.
Member Function Documentation
abs()
Real Geometry::Point::abs () const inline
Definition at line 25 of file geo.hpp.
References norm().
arg()
Real Geometry::Point::arg () const inline
Definition at line 26 of file geo.hpp.
References x, and y.
cross() [1/2]
Real Geometry::Point::cross (const Point & p) const inline
Definition at line 22 of file geo.hpp.
References x, and y.
cross() [2/2]
Real Geometry::Point::cross (const Point & p1, const Point & p2) const inline
Definition at line 23 of file geo.hpp.
References x, and y.
dot()
Real Geometry::Point::dot (const Point & p) const inline
Definition at line 21 of file geo.hpp.
References x, and y.
norm()
Real Geometry::Point::norm () const inline
Definition at line 24 of file geo.hpp.
References x, and y.
operator*()
Point Geometry::Point::operator* (Real k) const inline
Definition at line 19 of file geo.hpp.
References Point(), x, and y.
operator+()
Point Geometry::Point::operator+ (const Point & p) const inline
Definition at line 17 of file geo.hpp.
References Point(), x, and y.
operator-()
Point Geometry::Point::operator- (const Point & p) const inline
Definition at line 18 of file geo.hpp.
References Point(), x, and y.
operator/()
Point Geometry::Point::operator/ (Real k) const inline
Definition at line 20 of file geo.hpp.
References Point(), x, and y.
operator==()
bool Geometry::Point::operator== (const Point & p) const inline
Definition at line 27 of file geo.hpp.
References Geometry::almostEqual(), x, and y.
Friends And Related Symbol Documentation
operator>>
istream & operator>> (istream & is, Point & p) friend
Definition at line 28 of file geo.hpp.
References x, and y.
Member Data Documentation
x
Real Geometry::Point::x
Definition at line 14 of file geo.hpp.
y
Real Geometry::Point::y
Definition at line 14 of file geo.hpp.
The documentation for this struct was generated from the following file:
geometry/geo.hpp